local M = {}

M.name = "nvchad-chocolate"
M.label = "NvChad Chocolate"
M.source = "chocolate"
M.background = "dark"

M.highlights = {
  ["@annotation"] = { fg = "#ab9382" },
  ["@attribute"] = { fg = "#829e9b" },
  ["@character"] = { fg = "#c65f5f" },
  ["@comment"] = { fg = "#575453" },
  ["@comment.danger"] = { fg = "#2b2827", bg = "#c65f5f" },
  ["@comment.note"] = { fg = "#252221", bg = "#7d92a2" },
  ["@comment.todo"] = { fg = "#4d4a49", bg = "#cdc0ad" },
  ["@comment.warning"] = { fg = "#2b2827", bg = "#d08b65" },
  ["@constant"] = { fg = "#d08b65" },
  ["@constant.builtin"] = { fg = "#d08b65" },
  ["@constant.macro"] = { fg = "#c65f5f" },
  ["@constructor"] = { fg = "#998396" },
  ["@definition"] = { sp = "#43403f", underline = true },
  ["@diff.delta"] = { fg = "#6b6867" },
  ["@diff.minus"] = { fg = "#c65f5f" },
  ["@diff.plus"] = { fg = "#8ca589" },
  ["@error"] = { fg = "#c65f5f" },
  ["@function"] = { fg = "#7d92a2" },
  ["@function.builtin"] = { fg = "#d9b27c" },
  ["@function.call"] = { fg = "#7d92a2" },
  ["@function.macro"] = { fg = "#c65f5f" },
  ["@function.method"] = { fg = "#7d92a2" },
  ["@function.method.call"] = { fg = "#7d92a2" },
  ["@ibl.scope.underline.1"] = { bg = "#2b2827" },
  ["@ibl.scope.underline.2"] = { bg = "#2b2827" },
  ["@ibl.scope.underline.3"] = { bg = "#2b2827" },
  ["@ibl.scope.underline.4"] = { bg = "#2b2827" },
  ["@ibl.scope.underline.5"] = { bg = "#2b2827" },
  ["@ibl.scope.underline.6"] = { bg = "#2b2827" },
  ["@ibl.scope.underline.7"] = { bg = "#2b2827" },
  ["@keyword"] = { fg = "#c65f5f" },
  ["@keyword.conditional"] = { fg = "#c65f5f" },
  ["@keyword.conditional.ternary"] = { fg = "#c65f5f" },
  ["@keyword.directive"] = { fg = "#d9b27c" },
  ["@keyword.directive.define"] = { fg = "#c65f5f" },
  ["@keyword.exception"] = { fg = "#c65f5f" },
  ["@keyword.function"] = { fg = "#c65f5f" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.operator"] = { fg = "#c65f5f" },
  ["@keyword.repeat"] = { fg = "#d9b27c" },
  ["@keyword.return"] = { fg = "#c65f5f" },
  ["@keyword.storage"] = { fg = "#d9b27c" },
  ["@markup.heading"] = { fg = "#7d92a2" },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = "#c65f5f" },
  ["@markup.link.label"] = { fg = "#998396" },
  ["@markup.link.url"] = { fg = "#d08b65", underline = true },
  ["@markup.list"] = { fg = "#c65f5f" },
  ["@markup.quote"] = { bg = "#2b2827" },
  ["@markup.raw"] = { fg = "#d08b65" },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@module"] = { fg = "#ab9382" },
  ["@number"] = { fg = "#d08b65" },
  ["@number.float"] = { fg = "#d08b65" },
  ["@operator"] = { fg = "#c8bAA4" },
  ["@parenthesis"] = { link = "@punctuation.bracket" },
  ["@property"] = { fg = "#c65f5f" },
  ["@punctuation.bracket"] = { fg = "#beae94" },
  ["@punctuation.delimiter"] = { fg = "#ab9382" },
  ["@reference"] = { fg = "#c8bAA4" },
  ["@scope"] = { bold = true },
  ["@string"] = { fg = "#8ca589" },
  ["@string.escape"] = { fg = "#998396" },
  ["@string.regex"] = { fg = "#998396" },
  ["@symbol"] = { fg = "#8ca589" },
  ["@tag"] = { fg = "#d9b27c" },
  ["@tag.attribute"] = { fg = "#c65f5f" },
  ["@tag.delimiter"] = { fg = "#ab9382" },
  ["@text"] = { fg = "#c8bAA4" },
  ["@text.emphasis"] = { fg = "#d08b65" },
  ["@text.strike"] = { fg = "#ab9382", strikethrough = true },
  ["@type.builtin"] = { fg = "#d9b27c" },
  ["@variable"] = { fg = "#beae94" },
  ["@variable.builtin"] = { fg = "#d08b65" },
  ["@variable.member"] = { fg = "#998396" },
  ["@variable.member.key"] = { fg = "#c65f5f" },
  ["@variable.parameter"] = { fg = "#8ca589" },
  ["BlinkCmpDoc"] = { bg = "#252221" },
  ["BlinkCmpDocBorder"] = { fg = "#575453" },
  ["BlinkCmpDocCursorLine"] = { bg = "#2f2c2b" },
  ["BlinkCmpDocSeparator"] = { fg = "#4d4a49" },
  ["BlinkCmpGhostText"] = { fg = "#575453" },
  ["BlinkCmpKindClass"] = { fg = "#749689" },
  ["BlinkCmpKindCodeium"] = { fg = "#95ae92" },
  ["BlinkCmpKindColor"] = { fg = "#cdc0ad" },
  ["BlinkCmpKindConstant"] = { fg = "#d08b65" },
  ["BlinkCmpKindConstructor"] = { fg = "#7d92a2" },
  ["BlinkCmpKindCopilot"] = { fg = "#8ca589" },
  ["BlinkCmpKindEnum"] = { fg = "#7d92a2" },
  ["BlinkCmpKindEnumMember"] = { fg = "#998396" },
  ["BlinkCmpKindEvent"] = { fg = "#d9b27c" },
  ["BlinkCmpKindField"] = { fg = "#c65f5f" },
  ["BlinkCmpKindFile"] = { fg = "#cdc0ad" },
  ["BlinkCmpKindFolder"] = { fg = "#cdc0ad" },
  ["BlinkCmpKindFunction"] = { fg = "#7d92a2" },
  ["BlinkCmpKindIdentifier"] = { fg = "#c65f5f" },
  ["BlinkCmpKindInterface"] = { fg = "#8ca589" },
  ["BlinkCmpKindKeyword"] = { fg = "#cdc0ad" },
  ["BlinkCmpKindMethod"] = { fg = "#7d92a2" },
  ["BlinkCmpKindModule"] = { fg = "#d9b27c" },
  ["BlinkCmpKindOperator"] = { fg = "#c8bAA4" },
  ["BlinkCmpKindProperty"] = { fg = "#c65f5f" },
  ["BlinkCmpKindReference"] = { fg = "#c8bAA4" },
  ["BlinkCmpKindSnippet"] = { fg = "#c65f5f" },
  ["BlinkCmpKindStruct"] = { fg = "#c65f5f" },
  ["BlinkCmpKindStructure"] = { fg = "#c65f5f" },
  ["BlinkCmpKindSuperMaven"] = { fg = "#d9b27c" },
  ["BlinkCmpKindTabNine"] = { fg = "#dc7575" },
  ["BlinkCmpKindText"] = { fg = "#8ca589" },
  ["BlinkCmpKindType"] = { fg = "#d9b27c" },
  ["BlinkCmpKindTypeParameter"] = { fg = "#c65f5f" },
  ["BlinkCmpKindUnit"] = { fg = "#c65f5f" },
  ["BlinkCmpKindValue"] = { fg = "#829e9b" },
  ["BlinkCmpKindVariable"] = { fg = "#c65f5f" },
  ["BlinkCmpLabel"] = { fg = "#cdc0ad" },
  ["BlinkCmpLabelDeprecated"] = { fg = "#c65f5f", strikethrough = true },
  ["BlinkCmpLabelDescription"] = { fg = "#6b6867" },
  ["BlinkCmpLabelDetail"] = { fg = "#6b6867" },
  ["BlinkCmpLabelMatch"] = { fg = "#7d92a2", bold = true },
  ["BlinkCmpMenu"] = { bg = "#252221" },
  ["BlinkCmpMenuBorder"] = { fg = "#575453" },
  ["BlinkCmpMenuSelection"] = { bold = true, link = "PmenuSel" },
  ["BlinkCmpScrollBarGutter"] = { bg = "#2b2827" },
  ["BlinkCmpScrollBarThumb"] = { bg = "#4d4a49" },
  ["BlinkCmpSignatureHelp"] = { bg = "#252221" },
  ["BlinkCmpSignatureHelpActiveParameter"] = { fg = "#7d92a2", bold = true },
  ["BlinkCmpSignatureHelpBorder"] = { fg = "#575453" },
  ["BlinkCmpSource"] = { fg = "#575453" },
  ["Boolean"] = { fg = "#d08b65" },
  ["Character"] = { fg = "#c65f5f" },
  ["CmpBorder"] = { fg = "#575453" },
  ["CmpDoc"] = { bg = "#252221" },
  ["CmpDocBorder"] = { fg = "#575453" },
  ["CmpItemAbbr"] = { fg = "#cdc0ad" },
  ["CmpItemAbbrMatch"] = { fg = "#7d92a2", bold = true },
  ["CmpItemKindClass"] = { fg = "#749689" },
  ["CmpItemKindCodeium"] = { fg = "#95ae92" },
  ["CmpItemKindColor"] = { fg = "#cdc0ad" },
  ["CmpItemKindConstant"] = { fg = "#d08b65" },
  ["CmpItemKindConstructor"] = { fg = "#7d92a2" },
  ["CmpItemKindCopilot"] = { fg = "#8ca589" },
  ["CmpItemKindEnum"] = { fg = "#7d92a2" },
  ["CmpItemKindEnumMember"] = { fg = "#998396" },
  ["CmpItemKindEvent"] = { fg = "#d9b27c" },
  ["CmpItemKindField"] = { fg = "#c65f5f" },
  ["CmpItemKindFile"] = { fg = "#cdc0ad" },
  ["CmpItemKindFolder"] = { fg = "#cdc0ad" },
  ["CmpItemKindFunction"] = { fg = "#7d92a2" },
  ["CmpItemKindIdentifier"] = { fg = "#c65f5f" },
  ["CmpItemKindInterface"] = { fg = "#8ca589" },
  ["CmpItemKindKeyword"] = { fg = "#cdc0ad" },
  ["CmpItemKindMethod"] = { fg = "#7d92a2" },
  ["CmpItemKindModule"] = { fg = "#d9b27c" },
  ["CmpItemKindOperator"] = { fg = "#c8bAA4" },
  ["CmpItemKindProperty"] = { fg = "#c65f5f" },
  ["CmpItemKindReference"] = { fg = "#c8bAA4" },
  ["CmpItemKindSnippet"] = { fg = "#c65f5f" },
  ["CmpItemKindStruct"] = { fg = "#c65f5f" },
  ["CmpItemKindStructure"] = { fg = "#c65f5f" },
  ["CmpItemKindSuperMaven"] = { fg = "#d9b27c" },
  ["CmpItemKindTabNine"] = { fg = "#dc7575" },
  ["CmpItemKindText"] = { fg = "#8ca589" },
  ["CmpItemKindType"] = { fg = "#d9b27c" },
  ["CmpItemKindTypeParameter"] = { fg = "#c65f5f" },
  ["CmpItemKindUnit"] = { fg = "#c65f5f" },
  ["CmpItemKindValue"] = { fg = "#829e9b" },
  ["CmpItemKindVariable"] = { fg = "#c65f5f" },
  ["CmpPmenu"] = { bg = "#252221" },
  ["CmpSel"] = { bold = true, link = "PmenuSel" },
  ["Conditional"] = { fg = "#c65f5f" },
  ["Constant"] = { fg = "#d08b65" },
  ["Define"] = { fg = "#c65f5f", sp = "none" },
  ["Delimiter"] = { fg = "#ab9382" },
  ["DevIconDart"] = { fg = "#829e9b" },
  ["DevIconDockerfile"] = { fg = "#829e9b" },
  ["DevIconJSX"] = { fg = "#7d92a2" },
  ["DevIconJava"] = { fg = "#d08b65" },
  ["DevIconMd"] = { fg = "#7d92a2" },
  ["DevIconSvelte"] = { fg = "#c65f5f" },
  ["DevIconTSX"] = { fg = "#7d92a2" },
  ["DevIconZig"] = { fg = "#d08b65" },
  ["DevIconc"] = { fg = "#7d92a2" },
  ["DevIconcss"] = { fg = "#7d92a2" },
  ["DevIcondeb"] = { fg = "#829e9b" },
  ["DevIconhtml"] = { fg = "#dc7575" },
  ["DevIconjpeg"] = { fg = "#917b8e" },
  ["DevIconjpg"] = { fg = "#917b8e" },
  ["DevIconjs"] = { fg = "#e1ba84" },
  ["DevIconkt"] = { fg = "#d08b65" },
  ["DevIconlock"] = { fg = "#c65f5f" },
  ["DevIconlua"] = { fg = "#7d92a2" },
  ["DevIconmp3"] = { fg = "#cdc0ad" },
  ["DevIconmp4"] = { fg = "#cdc0ad" },
  ["DevIconout"] = { fg = "#cdc0ad" },
  ["DevIconpng"] = { fg = "#917b8e" },
  ["DevIconpy"] = { fg = "#829e9b" },
  ["DevIconrb"] = { fg = "#d16a6a" },
  ["DevIconrpm"] = { fg = "#d08b65" },
  ["DevIcontoml"] = { fg = "#7d92a2" },
  ["DevIconts"] = { fg = "#749689" },
  ["DevIconttf"] = { fg = "#cdc0ad" },
  ["DevIconvue"] = { fg = "#95ae92" },
  ["DevIconwoff"] = { fg = "#cdc0ad" },
  ["DevIconwoff2"] = { fg = "#cdc0ad" },
  ["DevIconxz"] = { fg = "#e1ba84" },
  ["DevIconzip"] = { fg = "#e1ba84" },
  ["DiagnosticError"] = { fg = "#c65f5f" },
  ["DiagnosticHint"] = { fg = "#998396" },
  ["DiagnosticInfo"] = { fg = "#8ca589" },
  ["DiagnosticWarn"] = { fg = "#d9b27c" },
  ["DiffAdd"] = { fg = "#8ca589", bg = "#2f2f2b" },
  ["DiffAdded"] = { fg = "#8ca589", bg = "#2f2f2b" },
  ["DiffChange"] = { fg = "#6b6867", bg = "#2c2928" },
  ["DiffChangeDelete"] = { fg = "#c65f5f", bg = "#352827" },
  ["DiffDelete"] = { fg = "#c65f5f", bg = "#352827" },
  ["DiffModified"] = { fg = "#d08b65", bg = "#362c27" },
  ["DiffRemoved"] = { fg = "#c65f5f", bg = "#352827" },
  ["DiffText"] = { fg = "#cdc0ad", bg = "#2b2827" },
  ["Float"] = { fg = "#d08b65" },
  ["Function"] = { fg = "#7d92a2" },
  ["IblChar"] = { fg = "#322f2e" },
  ["IblScopeChar"] = { fg = "#4d4a49" },
  ["Identifier"] = { fg = "#c65f5f", sp = "none" },
  ["Include"] = { fg = "#7d92a2" },
  ["Keyword"] = { fg = "#c65f5f" },
  ["Label"] = { fg = "#d9b27c" },
  ["LspInlayHint"] = { fg = "#6b6867", bg = "#2b2827" },
  ["LspReferenceRead"] = { bg = "#43403f" },
  ["LspReferenceText"] = { bg = "#43403f" },
  ["LspReferenceWrite"] = { bg = "#43403f" },
  ["LspSignatureActiveParameter"] = { fg = "#252221", bg = "#8ca589" },
  ["MasonHeader"] = { fg = "#252221", bg = "#c65f5f" },
  ["MasonHeaderSecondary"] = { link = "MasonHighlightBlock" },
  ["MasonHighlight"] = { fg = "#7d92a2" },
  ["MasonHighlightBlock"] = { fg = "#252221", bg = "#8ca589" },
  ["MasonHighlightBlockBold"] = { link = "MasonHighlightBlock" },
  ["MasonMuted"] = { fg = "#6b6867" },
  ["MasonMutedBlock"] = { fg = "#6b6867", bg = "#2f2c2b" },
  ["Number"] = { fg = "#d08b65" },
  ["NvimTreeCursorLine"] = { bg = "#252221" },
  ["NvimTreeDiagnosticErrorFileHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticErrorFolderHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticHintFileHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticHintFolderHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticInfoFileHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticInfoFolderHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticWarnFileHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeDiagnosticWarnFolderHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeEmptyFolderName"] = { fg = "#768b9b" },
  ["NvimTreeEndOfBuffer"] = { fg = "#201d1c" },
  ["NvimTreeFolderArrowClosed"] = { fg = "#575453" },
  ["NvimTreeFolderArrowOpen"] = { fg = "#768b9b" },
  ["NvimTreeFolderIcon"] = { fg = "#768b9b" },
  ["NvimTreeFolderName"] = { fg = "#768b9b" },
  ["NvimTreeGitDeleted"] = { fg = "#c65f5f" },
  ["NvimTreeGitDirty"] = { fg = "#c65f5f" },
  ["NvimTreeGitIgnored"] = { fg = "#6b6867" },
  ["NvimTreeGitNew"] = { fg = "#d9b27c" },
  ["NvimTreeIndentMarker"] = { fg = "#2c2a29" },
  ["NvimTreeNormal"] = { bg = "#201d1c" },
  ["NvimTreeNormalNC"] = { bg = "#201d1c" },
  ["NvimTreeOpenedFolderName"] = { fg = "#768b9b" },
  ["NvimTreeRootFolder"] = { fg = "#c65f5f", bold = true },
  ["NvimTreeSpecialFile"] = { fg = "#d9b27c", bold = true },
  ["NvimTreeWinSeparator"] = { fg = "#201d1c", bg = "#201d1c" },
  ["NvimTreeWindowPicker"] = { fg = "#c65f5f", bg = "#2b2827" },
  ["Operator"] = { fg = "#7d92a2", sp = "none" },
  ["PreProc"] = { fg = "#d9b27c" },
  ["Repeat"] = { fg = "#d9b27c" },
  ["Special"] = { fg = "#998396" },
  ["SpecialChar"] = { fg = "#ab9382" },
  ["Statement"] = { fg = "#c65f5f" },
  ["StorageClass"] = { fg = "#d9b27c" },
  ["String"] = { fg = "#8ca589" },
  ["Structure"] = { fg = "#c65f5f" },
  ["TBTabTitle"] = { fg = "#252221", bg = "#7d92a2" },
  ["Tabline"] = { bg = "#2b2827" },
  ["Tag"] = { fg = "#d9b27c" },
  ["TbBufOff"] = { fg = "#6b6867", bg = "#2b2827" },
  ["TbBufOffClose"] = { fg = "#6b6867", bg = "#2b2827" },
  ["TbBufOffModified"] = { fg = "#c65f5f", bg = "#2b2827" },
  ["TbBufOn"] = { fg = "#cdc0ad", bg = "#252221" },
  ["TbBufOnClose"] = { fg = "#c65f5f", bg = "#252221" },
  ["TbBufOnModified"] = { fg = "#8ca589", bg = "#252221" },
  ["TbCloseAllBufsBtn"] = { fg = "#252221", bg = "#c65f5f", bold = true },
  ["TbFill"] = { bg = "#2b2827" },
  ["TbTabCloseBtn"] = { fg = "#252221", bg = "#728797" },
  ["TbTabNewBtn"] = { fg = "#cdc0ad", bg = "#393635" },
  ["TbTabOff"] = { fg = "#cdc0ad", bg = "#2b2827" },
  ["TbTabOn"] = { fg = "#c65f5f", bg = "#252221" },
  ["TbThemeToggleBtn"] = { fg = "#cdc0ad", bg = "#43403f", bold = true },
  ["TelescopeBorder"] = { fg = "#43403f" },
  ["TelescopeMatching"] = { fg = "#7d92a2", bg = "#2f2c2b" },
  ["TelescopeNormal"] = { bg = "none" },
  ["TelescopePreviewTitle"] = { fg = "#252221", bg = "#7d92a2" },
  ["TelescopePromptBorder"] = { fg = "#43403f" },
  ["TelescopePromptNormal"] = { bg = "none" },
  ["TelescopePromptPrefix"] = { fg = "#c65f5f", bg = "none" },
  ["TelescopePromptTitle"] = { fg = "#252221", bg = "#c65f5f" },
  ["TelescopeResultsDiffAdd"] = { fg = "#8ca589" },
  ["TelescopeResultsDiffChange"] = { fg = "#d9b27c" },
  ["TelescopeResultsDiffDelete"] = { fg = "#c65f5f" },
  ["TelescopeResultsTitle"] = { fg = "#252221", bg = "#8ca589" },
  ["TelescopeSelection"] = { fg = "#cdc0ad", bg = "#2b2827" },
  ["Todo"] = { fg = "#d9b27c", bg = "#2b2827" },
  ["Type"] = { fg = "#d9b27c", sp = "none" },
  ["Typedef"] = { fg = "#d9b27c" },
  ["Variable"] = { fg = "#c8bAA4" },
  ["WhichKey"] = { fg = "#7d92a2" },
  ["WhichKeyDesc"] = { fg = "#c65f5f" },
  ["WhichKeyGroup"] = { fg = "#8ca589" },
  ["WhichKeySeparator"] = { fg = "#6b6867" },
  ["WhichKeyValue"] = { fg = "#8ca589" },
  ["diffNewFile"] = { fg = "#7d92a2" },
  ["diffOldFile"] = { fg = "#dc7575" },
  ["gitcommitBranch"] = { fg = "#d08b65", bold = true },
  ["gitcommitComment"] = { fg = "#393635" },
  ["gitcommitDiscarded"] = { fg = "#393635" },
  ["gitcommitDiscardedFile"] = { fg = "#c65f5f", bold = true },
  ["gitcommitDiscardedType"] = { fg = "#7d92a2" },
  ["gitcommitHeader"] = { fg = "#c65f5f" },
  ["gitcommitOverflow"] = { fg = "#c65f5f" },
  ["gitcommitSelected"] = { fg = "#393635" },
  ["gitcommitSelectedFile"] = { fg = "#8ca589", bold = true },
  ["gitcommitSelectedType"] = { fg = "#7d92a2" },
  ["gitcommitSummary"] = { fg = "#8ca589" },
  ["gitcommitUnmergedFile"] = { fg = "#c65f5f", bold = true },
  ["gitcommitUnmergedType"] = { fg = "#7d92a2" },
  ["gitcommitUntracked"] = { fg = "#393635" },
  ["gitcommitUntrackedFile"] = { fg = "#d9b27c" },
}

function M.apply()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.background = M.background
  vim.g.colors_name = M.name
  for group, hl in pairs(M.highlights) do
    vim.api.nvim_set_hl(0, group, hl)
  end
  vim.api.nvim_exec_autocmds("ColorScheme", { pattern = M.name })
end

return M
