local M = {}

M.name = "nvchad-eldritch"
M.label = "NvChad Eldritch"
M.source = "eldritch"
M.background = "dark"

M.highlights = {
  ["@annotation"] = { fg = "#F16C75" },
  ["@attribute"] = { fg = "#F265B5" },
  ["@character"] = { fg = "#F16C75" },
  ["@comment"] = { fg = "#5866A2" },
  ["@comment.danger"] = { fg = "#202338", bg = "#F16C75" },
  ["@comment.note"] = { fg = "#171928", bg = "#04D1F9" },
  ["@comment.todo"] = { fg = "#444B78", bg = "#EBFAFA" },
  ["@comment.warning"] = { fg = "#202338", bg = "#F16C75" },
  ["@constant"] = { fg = "#A48CF2" },
  ["@constant.builtin"] = { fg = "#F16C75" },
  ["@constant.macro"] = { fg = "#F16C75" },
  ["@constructor"] = { fg = "#6770AA" },
  ["@definition"] = { sp = "#8386A8", underline = true },
  ["@diff.delta"] = { fg = "#6770AA" },
  ["@diff.minus"] = { fg = "#F16C75" },
  ["@diff.plus"] = { fg = "#37F499" },
  ["@error"] = { fg = "#F16C75" },
  ["@function"] = { fg = "#F265B5" },
  ["@function.builtin"] = { fg = "#04D1F9" },
  ["@function.call"] = { fg = "#F265B5" },
  ["@function.macro"] = { fg = "#A48CF2" },
  ["@function.method"] = { fg = "#7081D0" },
  ["@function.method.call"] = { fg = "#F265B5" },
  ["@ibl.scope.underline.1"] = { bg = "#202338" },
  ["@ibl.scope.underline.2"] = { bg = "#202338" },
  ["@ibl.scope.underline.3"] = { bg = "#202338" },
  ["@ibl.scope.underline.4"] = { bg = "#202338" },
  ["@ibl.scope.underline.5"] = { bg = "#202338" },
  ["@ibl.scope.underline.6"] = { bg = "#202338" },
  ["@ibl.scope.underline.7"] = { bg = "#202338" },
  ["@keyword"] = { fg = "#37F499" },
  ["@keyword.conditional"] = { fg = "#37F499" },
  ["@keyword.conditional.ternary"] = { fg = "#A48CF2" },
  ["@keyword.directive"] = { fg = "#37F499" },
  ["@keyword.directive.define"] = { fg = "#A48CF2" },
  ["@keyword.exception"] = { fg = "#F16C75" },
  ["@keyword.function"] = { fg = "#37F499" },
  ["@keyword.import"] = { fg = "#37F499", link = "Include" },
  ["@keyword.import.tsx"] = { fg = "#37F499" },
  ["@keyword.operator"] = { fg = "#A48CF2" },
  ["@keyword.repeat"] = { fg = "#37F499" },
  ["@keyword.return"] = { fg = "#37F499" },
  ["@keyword.storage"] = { fg = "#37F499" },
  ["@markup.heading"] = { fg = "#7081D0" },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = "#F16C75" },
  ["@markup.link.label"] = { fg = "#04D1F9" },
  ["@markup.link.url"] = { fg = "#F16C75", underline = true },
  ["@markup.list"] = { fg = "#F16C75" },
  ["@markup.quote"] = { bg = "#202338" },
  ["@markup.raw"] = { fg = "#F16C75" },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@module"] = { fg = "#F16C75" },
  ["@number"] = { fg = "#F16C75" },
  ["@number.float"] = { fg = "#F16C75" },
  ["@operator"] = { fg = "#04D1F9" },
  ["@property"] = { fg = "#A48CF2" },
  ["@punctuation.bracket"] = { fg = "#6770AA" },
  ["@punctuation.delimiter"] = { fg = "#6770AA" },
  ["@reference"] = { fg = "#ABB4DA" },
  ["@scope"] = { bold = true },
  ["@string"] = { fg = "#F1FC79" },
  ["@string.escape"] = { fg = "#04D1F9" },
  ["@string.regex"] = { fg = "#04D1F9" },
  ["@symbol"] = { fg = "#F1FC79" },
  ["@tag"] = { fg = "#04D1F9" },
  ["@tag.attribute"] = { fg = "#F16C75" },
  ["@tag.delimiter"] = { fg = "#6770AA" },
  ["@text"] = { fg = "#ABB4DA" },
  ["@text.emphasis"] = { fg = "#F16C75" },
  ["@text.strike"] = { fg = "#F16C75", strikethrough = true },
  ["@type.builtin"] = { fg = "#04D1F9" },
  ["@variable"] = { fg = "#A48CF2" },
  ["@variable.builtin"] = { fg = "#F16C75" },
  ["@variable.member"] = { fg = "#F265B5" },
  ["@variable.member.key"] = { fg = "#F16C75" },
  ["@variable.parameter"] = { fg = "#A48CF2" },
  ["BlinkCmpDoc"] = { bg = "#171928" },
  ["BlinkCmpDocBorder"] = { fg = "#4D5588" },
  ["BlinkCmpDocCursorLine"] = { bg = "#292D48" },
  ["BlinkCmpDocSeparator"] = { fg = "#444B78" },
  ["BlinkCmpGhostText"] = { fg = "#4D5588" },
  ["BlinkCmpKindClass"] = { fg = "#33C57F" },
  ["BlinkCmpKindCodeium"] = { fg = "#00FA82" },
  ["BlinkCmpKindColor"] = { fg = "#EBFAFA" },
  ["BlinkCmpKindConstant"] = { fg = "#F16C75" },
  ["BlinkCmpKindConstructor"] = { fg = "#04D1F9" },
  ["BlinkCmpKindCopilot"] = { fg = "#37F499" },
  ["BlinkCmpKindEnum"] = { fg = "#04D1F9" },
  ["BlinkCmpKindEnumMember"] = { fg = "#A48CF2" },
  ["BlinkCmpKindEvent"] = { fg = "#F1FC79" },
  ["BlinkCmpKindField"] = { fg = "#F16C75" },
  ["BlinkCmpKindFile"] = { fg = "#FFFFFF" },
  ["BlinkCmpKindFolder"] = { fg = "#FFFFFF" },
  ["BlinkCmpKindFunction"] = { fg = "#7081D0" },
  ["BlinkCmpKindIdentifier"] = { fg = "#F16C75" },
  ["BlinkCmpKindInterface"] = { fg = "#37F499" },
  ["BlinkCmpKindKeyword"] = { fg = "#FFFFFF" },
  ["BlinkCmpKindMethod"] = { fg = "#7081D0" },
  ["BlinkCmpKindModule"] = { fg = "#F7C67F" },
  ["BlinkCmpKindOperator"] = { fg = "#ABB4DA" },
  ["BlinkCmpKindProperty"] = { fg = "#F16C75" },
  ["BlinkCmpKindReference"] = { fg = "#ABB4DA" },
  ["BlinkCmpKindSnippet"] = { fg = "#F16C75" },
  ["BlinkCmpKindStruct"] = { fg = "#A48CF2" },
  ["BlinkCmpKindStructure"] = { fg = "#A48CF2" },
  ["BlinkCmpKindSuperMaven"] = { fg = "#F1FC79" },
  ["BlinkCmpKindTabNine"] = { fg = "#F265B5" },
  ["BlinkCmpKindText"] = { fg = "#F1FC79" },
  ["BlinkCmpKindType"] = { fg = "#F7C67F" },
  ["BlinkCmpKindTypeParameter"] = { fg = "#F16C75" },
  ["BlinkCmpKindUnit"] = { fg = "#A48CF2" },
  ["BlinkCmpKindValue"] = { fg = "#04D1F9" },
  ["BlinkCmpKindVariable"] = { fg = "#A48CF2" },
  ["BlinkCmpLabel"] = { fg = "#EBFAFA" },
  ["BlinkCmpLabelDeprecated"] = { fg = "#F16C75", strikethrough = true },
  ["BlinkCmpLabelDescription"] = { fg = "#6770AA" },
  ["BlinkCmpLabelDetail"] = { fg = "#6770AA" },
  ["BlinkCmpLabelMatch"] = { fg = "#04D1F9", bold = true },
  ["BlinkCmpMenu"] = { bg = "#171928" },
  ["BlinkCmpMenuBorder"] = { fg = "#4D5588" },
  ["BlinkCmpMenuSelection"] = { bold = true, link = "PmenuSel" },
  ["BlinkCmpScrollBarGutter"] = { bg = "#202338" },
  ["BlinkCmpScrollBarThumb"] = { bg = "#444B78" },
  ["BlinkCmpSignatureHelp"] = { bg = "#171928" },
  ["BlinkCmpSignatureHelpActiveParameter"] = { fg = "#04D1F9", bold = true },
  ["BlinkCmpSignatureHelpBorder"] = { fg = "#4D5588" },
  ["BlinkCmpSource"] = { fg = "#4D5588" },
  ["Boolean"] = { fg = "#F16C75" },
  ["Character"] = { fg = "#F16C75" },
  ["CmpBorder"] = { fg = "#A48CF2" },
  ["CmpDoc"] = { bg = "#171928" },
  ["CmpDocBorder"] = { fg = "#4D5588" },
  ["CmpItemAbbr"] = { fg = "#EBFAFA" },
  ["CmpItemAbbrMatch"] = { fg = "#04D1F9", bold = true },
  ["CmpItemKindClass"] = { fg = "#33C57F" },
  ["CmpItemKindCodeium"] = { fg = "#00FA82" },
  ["CmpItemKindColor"] = { fg = "#EBFAFA" },
  ["CmpItemKindConstant"] = { fg = "#F16C75" },
  ["CmpItemKindConstructor"] = { fg = "#04D1F9" },
  ["CmpItemKindCopilot"] = { fg = "#37F499" },
  ["CmpItemKindEnum"] = { fg = "#04D1F9" },
  ["CmpItemKindEnumMember"] = { fg = "#A48CF2" },
  ["CmpItemKindEvent"] = { fg = "#F1FC79" },
  ["CmpItemKindField"] = { fg = "#F16C75" },
  ["CmpItemKindFile"] = { fg = "#FFFFFF" },
  ["CmpItemKindFolder"] = { fg = "#FFFFFF" },
  ["CmpItemKindFunction"] = { fg = "#7081D0" },
  ["CmpItemKindIdentifier"] = { fg = "#F16C75" },
  ["CmpItemKindInterface"] = { fg = "#37F499" },
  ["CmpItemKindKeyword"] = { fg = "#FFFFFF" },
  ["CmpItemKindMethod"] = { fg = "#7081D0" },
  ["CmpItemKindModule"] = { fg = "#F7C67F" },
  ["CmpItemKindOperator"] = { fg = "#ABB4DA" },
  ["CmpItemKindProperty"] = { fg = "#F16C75" },
  ["CmpItemKindReference"] = { fg = "#ABB4DA" },
  ["CmpItemKindSnippet"] = { fg = "#F16C75" },
  ["CmpItemKindStruct"] = { fg = "#A48CF2" },
  ["CmpItemKindStructure"] = { fg = "#A48CF2" },
  ["CmpItemKindSuperMaven"] = { fg = "#F1FC79" },
  ["CmpItemKindTabNine"] = { fg = "#F265B5" },
  ["CmpItemKindText"] = { fg = "#F1FC79" },
  ["CmpItemKindType"] = { fg = "#F7C67F" },
  ["CmpItemKindTypeParameter"] = { fg = "#F16C75" },
  ["CmpItemKindUnit"] = { fg = "#A48CF2" },
  ["CmpItemKindValue"] = { fg = "#04D1F9" },
  ["CmpItemKindVariable"] = { fg = "#A48CF2" },
  ["CmpPmenu"] = { bg = "#171928" },
  ["CmpSel"] = { bold = true, link = "PmenuSel" },
  ["Conditional"] = { fg = "#A48CF2" },
  ["Constant"] = { fg = "#F16C75" },
  ["Define"] = { fg = "#A48CF2", sp = "none" },
  ["Delimiter"] = { fg = "#F16C75" },
  ["DevIconDart"] = { fg = "#04D1F9" },
  ["DevIconDockerfile"] = { fg = "#04D1F9" },
  ["DevIconJSX"] = { fg = "#04D1F9" },
  ["DevIconJava"] = { fg = "#F7C67F" },
  ["DevIconMd"] = { fg = "#04D1F9" },
  ["DevIconSvelte"] = { fg = "#F16C75" },
  ["DevIconTSX"] = { fg = "#04D1F9" },
  ["DevIconZig"] = { fg = "#F7C67F" },
  ["DevIconc"] = { fg = "#04D1F9" },
  ["DevIconcss"] = { fg = "#04D1F9" },
  ["DevIcondeb"] = { fg = "#04D1F9" },
  ["DevIconhtml"] = { fg = "#F265B5" },
  ["DevIconjpeg"] = { fg = "#5866A2" },
  ["DevIconjpg"] = { fg = "#5866A2" },
  ["DevIconjs"] = { fg = "#E9F941" },
  ["DevIconkt"] = { fg = "#F7C67F" },
  ["DevIconlock"] = { fg = "#F16C75" },
  ["DevIconlua"] = { fg = "#04D1F9" },
  ["DevIconmp3"] = { fg = "#EBFAFA" },
  ["DevIconmp4"] = { fg = "#EBFAFA" },
  ["DevIconout"] = { fg = "#EBFAFA" },
  ["DevIconpng"] = { fg = "#5866A2" },
  ["DevIconpy"] = { fg = "#04D1F9" },
  ["DevIconrb"] = { fg = "#BF4F8E" },
  ["DevIconrpm"] = { fg = "#F7C67F" },
  ["DevIcontoml"] = { fg = "#04D1F9" },
  ["DevIconts"] = { fg = "#33C57F" },
  ["DevIconttf"] = { fg = "#EBFAFA" },
  ["DevIconvue"] = { fg = "#00FA82" },
  ["DevIconwoff"] = { fg = "#EBFAFA" },
  ["DevIconwoff2"] = { fg = "#EBFAFA" },
  ["DevIconxz"] = { fg = "#E9F941" },
  ["DevIconzip"] = { fg = "#E9F941" },
  ["DiagnosticError"] = { fg = "#F16C75" },
  ["DiagnosticHint"] = { fg = "#A48CF2" },
  ["DiagnosticInfo"] = { fg = "#37F499" },
  ["DiagnosticWarn"] = { fg = "#F1FC79" },
  ["DiffAdd"] = { fg = "#37F499", bg = "#1a2e33" },
  ["DiffAdded"] = { fg = "#37F499", bg = "#1a2e33" },
  ["DiffChange"] = { fg = "#6770AA", bg = "#1e2135" },
  ["DiffChangeDelete"] = { fg = "#F16C75", bg = "#2c212f" },
  ["DiffDelete"] = { fg = "#F16C75", bg = "#2c212f" },
  ["DiffModified"] = { fg = "#F7C67F", bg = "#2d2a30" },
  ["DiffRemoved"] = { fg = "#F16C75", bg = "#2c212f" },
  ["DiffText"] = { fg = "#EBFAFA", bg = "#202338" },
  ["Float"] = { fg = "#F16C75" },
  ["Function"] = { fg = "#F265B5" },
  ["IblChar"] = { fg = "#3B4261" },
  ["IblScopeChar"] = { fg = "#444B78" },
  ["Identifier"] = { fg = "#F16C75", sp = "none" },
  ["Include"] = { fg = "#37F499" },
  ["Keyword"] = { fg = "#A48CF2" },
  ["Label"] = { fg = "#F7C67F" },
  ["LspInlayHint"] = { fg = "#6770AA", bg = "#202338" },
  ["LspReferenceRead"] = { bg = "#323758" },
  ["LspReferenceText"] = { bg = "#323758" },
  ["LspReferenceWrite"] = { bg = "#323758" },
  ["LspSignatureActiveParameter"] = { fg = "#171928", bg = "#37F499" },
  ["MasonHeader"] = { fg = "#171928", bg = "#F16C75" },
  ["MasonHeaderSecondary"] = { link = "MasonHighlightBlock" },
  ["MasonHighlight"] = { fg = "#04D1F9" },
  ["MasonHighlightBlock"] = { fg = "#171928", bg = "#37F499" },
  ["MasonHighlightBlockBold"] = { link = "MasonHighlightBlock" },
  ["MasonMuted"] = { fg = "#6770AA" },
  ["MasonMutedBlock"] = { fg = "#6770AA", bg = "#292D48" },
  ["Number"] = { fg = "#F16C75" },
  ["NvimTreeCursorLine"] = { bg = "#171928" },
  ["NvimTreeDiagnosticErrorFileHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticErrorFolderHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticHintFileHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticHintFolderHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticInfoFileHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticInfoFolderHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticWarnFileHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeDiagnosticWarnFolderHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeEmptyFolderName"] = { fg = "#66E4FD" },
  ["NvimTreeEndOfBuffer"] = { fg = "#131421" },
  ["NvimTreeFolderArrowClosed"] = { fg = "#4D5588" },
  ["NvimTreeFolderArrowOpen"] = { fg = "#66E4FD" },
  ["NvimTreeFolderIcon"] = { fg = "#66E4FD" },
  ["NvimTreeFolderName"] = { fg = "#66E4FD" },
  ["NvimTreeGitDeleted"] = { fg = "#F16C75" },
  ["NvimTreeGitDirty"] = { fg = "#F16C75" },
  ["NvimTreeGitIgnored"] = { fg = "#6770AA" },
  ["NvimTreeGitNew"] = { fg = "#F1FC79" },
  ["NvimTreeIndentMarker"] = { fg = "#373d5a" },
  ["NvimTreeNormal"] = { bg = "#131421" },
  ["NvimTreeNormalNC"] = { bg = "#131421" },
  ["NvimTreeOpenedFolderName"] = { fg = "#66E4FD" },
  ["NvimTreeRootFolder"] = { fg = "#F16C75", bold = true },
  ["NvimTreeSpecialFile"] = { fg = "#F1FC79", bold = true },
  ["NvimTreeWinSeparator"] = { fg = "#131421", bg = "#131421" },
  ["NvimTreeWindowPicker"] = { fg = "#F16C75", bg = "#202338" },
  ["Operator"] = { fg = "#ABB4DA", sp = "none" },
  ["PreProc"] = { fg = "#F7C67F" },
  ["Repeat"] = { fg = "#F7C67F" },
  ["Special"] = { fg = "#A48CF2" },
  ["SpecialChar"] = { fg = "#F265B5" },
  ["Statement"] = { fg = "#F16C75" },
  ["StorageClass"] = { fg = "#F7C67F" },
  ["String"] = { fg = "#F1FC79" },
  ["Structure"] = { fg = "#A48CF2" },
  ["TBTabTitle"] = { fg = "#171928", bg = "#04D1F9" },
  ["Tabline"] = { bg = "#202338" },
  ["Tag"] = { fg = "#F7C67F" },
  ["TbBufOff"] = { fg = "#6770AA", bg = "#202338" },
  ["TbBufOffClose"] = { fg = "#6770AA", bg = "#202338" },
  ["TbBufOffModified"] = { fg = "#F16C75", bg = "#202338" },
  ["TbBufOn"] = { fg = "#EBFAFA", bg = "#171928" },
  ["TbBufOnClose"] = { fg = "#F16C75", bg = "#171928" },
  ["TbBufOnModified"] = { fg = "#37F499", bg = "#171928" },
  ["TbCloseAllBufsBtn"] = { fg = "#171928", bg = "#F16C75", bold = true },
  ["TbFill"] = { bg = "#202338" },
  ["TbTabCloseBtn"] = { fg = "#171928", bg = "#7081D0" },
  ["TbTabNewBtn"] = { fg = "#EBFAFA", bg = "#323758" },
  ["TbTabOff"] = { fg = "#EBFAFA", bg = "#202338" },
  ["TbTabOn"] = { fg = "#F16C75", bg = "#171928" },
  ["TbThemeToggleBtn"] = { fg = "#EBFAFA", bg = "#323758", bold = true },
  ["TelescopeBorder"] = { fg = "#323758", link = "FloatBorder" },
  ["TelescopeMatching"] = { fg = "#04D1F9", bg = "#292D48" },
  ["TelescopeNormal"] = { bg = "none" },
  ["TelescopePreviewTitle"] = { fg = "#171928", bg = "#04D1F9" },
  ["TelescopePromptBorder"] = { fg = "#323758", link = "FloatBorder" },
  ["TelescopePromptNormal"] = { bg = "none" },
  ["TelescopePromptPrefix"] = { fg = "#F16C75", bg = "none" },
  ["TelescopePromptTitle"] = { fg = "#171928", bg = "#F16C75" },
  ["TelescopeResultsDiffAdd"] = { fg = "#37F499" },
  ["TelescopeResultsDiffChange"] = { fg = "#F1FC79" },
  ["TelescopeResultsDiffDelete"] = { fg = "#F16C75" },
  ["TelescopeResultsTitle"] = { fg = "#171928", bg = "#37F499" },
  ["TelescopeSelection"] = { fg = "#EBFAFA", bg = "#171928", bold = true },
  ["Todo"] = { fg = "#F7C67F", bg = "#21253a" },
  ["Type"] = { fg = "#04D1F9", sp = "none" },
  ["Typedef"] = { fg = "#F7C67F" },
  ["Variable"] = { fg = "#ABB4DA" },
  ["WhichKey"] = { fg = "#04D1F9" },
  ["WhichKeyDesc"] = { fg = "#F16C75" },
  ["WhichKeyGroup"] = { fg = "#37F499" },
  ["WhichKeySeparator"] = { fg = "#6770AA" },
  ["WhichKeyValue"] = { fg = "#37F499" },
  ["diffNewFile"] = { fg = "#04D1F9" },
  ["diffOldFile"] = { fg = "#F265B5" },
  ["gitcommitBranch"] = { fg = "#F16C75", bold = true },
  ["gitcommitComment"] = { fg = "#3B4261" },
  ["gitcommitDiscarded"] = { fg = "#3B4261" },
  ["gitcommitDiscardedFile"] = { fg = "#F16C75", bold = true },
  ["gitcommitDiscardedType"] = { fg = "#7081D0" },
  ["gitcommitHeader"] = { fg = "#A48CF2" },
  ["gitcommitOverflow"] = { fg = "#F16C75" },
  ["gitcommitSelected"] = { fg = "#3B4261" },
  ["gitcommitSelectedFile"] = { fg = "#F1FC79", bold = true },
  ["gitcommitSelectedType"] = { fg = "#7081D0" },
  ["gitcommitSummary"] = { fg = "#F1FC79" },
  ["gitcommitUnmergedFile"] = { fg = "#F16C75", bold = true },
  ["gitcommitUnmergedType"] = { fg = "#7081D0" },
  ["gitcommitUntracked"] = { fg = "#3B4261" },
  ["gitcommitUntrackedFile"] = { fg = "#F7C67F" },
}

function M.apply()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.background = M.background
  vim.g.colors_name = M.name
  for group, hl in pairs(M.highlights) do
    vim.api.nvim_set_hl(0, group, hl)
  end
  vim.api.nvim_exec_autocmds("ColorScheme", { pattern = M.name })
end

return M
