local M = {}

M.name = "nvchad-flexoki"
M.label = "NvChad Flexoki"
M.source = "flexoki"
M.background = "dark"

M.highlights = {
  ["@annotation"] = { fg = "#519ABA" },
  ["@attribute"] = { fg = "#8B7EC8" },
  ["@character"] = { fg = "#D14D41" },
  ["@comment"] = { fg = "#555050" },
  ["@comment.danger"] = { fg = "#1c1b1b", bg = "#D14D41" },
  ["@comment.note"] = { fg = "#100F0F", bg = "#4385BE" },
  ["@comment.todo"] = { fg = "#393636", bg = "#CECDC3" },
  ["@comment.warning"] = { fg = "#1c1b1b", bg = "#DA702C" },
  ["@constant"] = { fg = "#DA702C" },
  ["@constant.builtin"] = { fg = "#DA702C" },
  ["@constant.macro"] = { fg = "#D14D41" },
  ["@constructor"] = { fg = "#3AA99F" },
  ["@definition"] = { sp = "#555050", underline = true },
  ["@diff.delta"] = { fg = "#6a6363" },
  ["@diff.minus"] = { fg = "#D14D41" },
  ["@diff.plus"] = { fg = "#879A39" },
  ["@error"] = { fg = "#D14D41" },
  ["@function"] = { fg = "#4385BE" },
  ["@function.builtin"] = { fg = "#4385BE" },
  ["@function.call"] = { fg = "#4385BE" },
  ["@function.macro"] = { fg = "#D14D41" },
  ["@function.method"] = { fg = "#4385BE" },
  ["@function.method.call"] = { fg = "#4385BE" },
  ["@ibl.scope.underline.1"] = { bg = "#1c1b1b" },
  ["@ibl.scope.underline.2"] = { bg = "#1c1b1b" },
  ["@ibl.scope.underline.3"] = { bg = "#1c1b1b" },
  ["@ibl.scope.underline.4"] = { bg = "#1c1b1b" },
  ["@ibl.scope.underline.5"] = { bg = "#1c1b1b" },
  ["@ibl.scope.underline.6"] = { bg = "#1c1b1b" },
  ["@ibl.scope.underline.7"] = { bg = "#1c1b1b" },
  ["@keyword"] = { fg = "#3AA99F" },
  ["@keyword.conditional"] = { fg = "#D0A215" },
  ["@keyword.conditional.ternary"] = { fg = "#D0A215" },
  ["@keyword.directive"] = { fg = "#8B7EC8" },
  ["@keyword.directive.define"] = { fg = "#D0A215" },
  ["@keyword.exception"] = { fg = "#D14D41" },
  ["@keyword.function"] = { fg = "#D0A215" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.operator"] = { fg = "#D0A215" },
  ["@keyword.repeat"] = { fg = "#8B7EC8" },
  ["@keyword.return"] = { fg = "#D0A215" },
  ["@keyword.storage"] = { fg = "#8B7EC8" },
  ["@markup.heading"] = { fg = "#4385BE" },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = "#D14D41" },
  ["@markup.link.label"] = { fg = "#3AA99F" },
  ["@markup.link.url"] = { fg = "#879A39", underline = true },
  ["@markup.list"] = { fg = "#D14D41" },
  ["@markup.quote"] = { bg = "#1c1b1b" },
  ["@markup.raw"] = { fg = "#DA702C" },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@module"] = { fg = "#D14D41" },
  ["@number"] = { fg = "#DA702C" },
  ["@number.float"] = { fg = "#DA702C" },
  ["@operator"] = { fg = "#CECDC3" },
  ["@property"] = { fg = "#D14D41" },
  ["@punctuation.bracket"] = { fg = "#D0A215" },
  ["@punctuation.delimiter"] = { fg = "#519ABA" },
  ["@reference"] = { fg = "#CECDC3" },
  ["@scope"] = { bold = true },
  ["@string"] = { fg = "#879A39" },
  ["@string.escape"] = { fg = "#3AA99F" },
  ["@string.regex"] = { fg = "#3AA99F" },
  ["@string.special.url"] = { fg = "#879A39" },
  ["@symbol"] = { fg = "#879A39" },
  ["@tag"] = { fg = "#4385BE" },
  ["@tag.attribute"] = { fg = "#DA702C" },
  ["@tag.delimiter"] = { fg = "#519ABA" },
  ["@text"] = { fg = "#CECDC3" },
  ["@text.emphasis"] = { fg = "#DA702C" },
  ["@text.strike"] = { fg = "#519ABA", strikethrough = true },
  ["@type.builtin"] = { fg = "#8B7EC8" },
  ["@variable"] = { fg = "#CECDC3" },
  ["@variable.builtin"] = { fg = "#DA702C" },
  ["@variable.member"] = { fg = "#D14D41" },
  ["@variable.member.key"] = { fg = "#D14D41" },
  ["@variable.parameter"] = { fg = "#d36da1" },
  ["BlinkCmpDoc"] = { bg = "#100F0F" },
  ["BlinkCmpDocBorder"] = { fg = "#555050" },
  ["BlinkCmpDocCursorLine"] = { bg = "#292626" },
  ["BlinkCmpDocSeparator"] = { fg = "#393636" },
  ["BlinkCmpGhostText"] = { fg = "#555050" },
  ["BlinkCmpKindClass"] = { fg = "#519ABA" },
  ["BlinkCmpKindCodeium"] = { fg = "#7e9f0e" },
  ["BlinkCmpKindColor"] = { fg = "#CECDC3" },
  ["BlinkCmpKindConstant"] = { fg = "#DA702C" },
  ["BlinkCmpKindConstructor"] = { fg = "#4385BE" },
  ["BlinkCmpKindCopilot"] = { fg = "#879A39" },
  ["BlinkCmpKindEnum"] = { fg = "#4385BE" },
  ["BlinkCmpKindEnumMember"] = { fg = "#8B7EC8" },
  ["BlinkCmpKindEvent"] = { fg = "#D0A215" },
  ["BlinkCmpKindField"] = { fg = "#D14D41" },
  ["BlinkCmpKindFile"] = { fg = "#c8ccd4" },
  ["BlinkCmpKindFolder"] = { fg = "#c8ccd4" },
  ["BlinkCmpKindFunction"] = { fg = "#4385BE" },
  ["BlinkCmpKindIdentifier"] = { fg = "#D14D41" },
  ["BlinkCmpKindInterface"] = { fg = "#879A39" },
  ["BlinkCmpKindKeyword"] = { fg = "#c8ccd4" },
  ["BlinkCmpKindMethod"] = { fg = "#4385BE" },
  ["BlinkCmpKindModule"] = { fg = "#8B7EC8" },
  ["BlinkCmpKindOperator"] = { fg = "#CECDC3" },
  ["BlinkCmpKindProperty"] = { fg = "#D14D41" },
  ["BlinkCmpKindReference"] = { fg = "#CECDC3" },
  ["BlinkCmpKindSnippet"] = { fg = "#D14D41" },
  ["BlinkCmpKindStruct"] = { fg = "#D0A215" },
  ["BlinkCmpKindStructure"] = { fg = "#D0A215" },
  ["BlinkCmpKindSuperMaven"] = { fg = "#D0A215" },
  ["BlinkCmpKindTabNine"] = { fg = "#d36da1" },
  ["BlinkCmpKindText"] = { fg = "#879A39" },
  ["BlinkCmpKindType"] = { fg = "#8B7EC8" },
  ["BlinkCmpKindTypeParameter"] = { fg = "#D14D41" },
  ["BlinkCmpKindUnit"] = { fg = "#D0A215" },
  ["BlinkCmpKindValue"] = { fg = "#3AA99F" },
  ["BlinkCmpKindVariable"] = { fg = "#D0A215" },
  ["BlinkCmpLabel"] = { fg = "#CECDC3" },
  ["BlinkCmpLabelDeprecated"] = { fg = "#D14D41", strikethrough = true },
  ["BlinkCmpLabelDescription"] = { fg = "#6a6363" },
  ["BlinkCmpLabelDetail"] = { fg = "#6a6363" },
  ["BlinkCmpLabelMatch"] = { fg = "#4385BE", bold = true },
  ["BlinkCmpMenu"] = { bg = "#100F0F" },
  ["BlinkCmpMenuBorder"] = { fg = "#555050" },
  ["BlinkCmpMenuSelection"] = { bold = true, link = "PmenuSel" },
  ["BlinkCmpScrollBarGutter"] = { bg = "#1c1b1b" },
  ["BlinkCmpScrollBarThumb"] = { bg = "#393636" },
  ["BlinkCmpSignatureHelp"] = { bg = "#100F0F" },
  ["BlinkCmpSignatureHelpActiveParameter"] = { fg = "#4385BE", bold = true },
  ["BlinkCmpSignatureHelpBorder"] = { fg = "#555050" },
  ["BlinkCmpSource"] = { fg = "#555050" },
  ["Boolean"] = { fg = "#DA702C" },
  ["Character"] = { fg = "#D14D41" },
  ["CmpBorder"] = { fg = "#555050" },
  ["CmpDoc"] = { bg = "#100F0F" },
  ["CmpDocBorder"] = { fg = "#555050" },
  ["CmpItemAbbr"] = { fg = "#CECDC3" },
  ["CmpItemAbbrMatch"] = { fg = "#4385BE", bold = true },
  ["CmpItemKindClass"] = { fg = "#519ABA" },
  ["CmpItemKindCodeium"] = { fg = "#7e9f0e" },
  ["CmpItemKindColor"] = { fg = "#CECDC3" },
  ["CmpItemKindConstant"] = { fg = "#DA702C" },
  ["CmpItemKindConstructor"] = { fg = "#4385BE" },
  ["CmpItemKindCopilot"] = { fg = "#879A39" },
  ["CmpItemKindEnum"] = { fg = "#4385BE" },
  ["CmpItemKindEnumMember"] = { fg = "#8B7EC8" },
  ["CmpItemKindEvent"] = { fg = "#D0A215" },
  ["CmpItemKindField"] = { fg = "#D14D41" },
  ["CmpItemKindFile"] = { fg = "#c8ccd4" },
  ["CmpItemKindFolder"] = { fg = "#c8ccd4" },
  ["CmpItemKindFunction"] = { fg = "#4385BE" },
  ["CmpItemKindIdentifier"] = { fg = "#D14D41" },
  ["CmpItemKindInterface"] = { fg = "#879A39" },
  ["CmpItemKindKeyword"] = { fg = "#c8ccd4" },
  ["CmpItemKindMethod"] = { fg = "#4385BE" },
  ["CmpItemKindModule"] = { fg = "#8B7EC8" },
  ["CmpItemKindOperator"] = { fg = "#CECDC3" },
  ["CmpItemKindProperty"] = { fg = "#D14D41" },
  ["CmpItemKindReference"] = { fg = "#CECDC3" },
  ["CmpItemKindSnippet"] = { fg = "#D14D41" },
  ["CmpItemKindStruct"] = { fg = "#D0A215" },
  ["CmpItemKindStructure"] = { fg = "#D0A215" },
  ["CmpItemKindSuperMaven"] = { fg = "#D0A215" },
  ["CmpItemKindTabNine"] = { fg = "#d36da1" },
  ["CmpItemKindText"] = { fg = "#879A39" },
  ["CmpItemKindType"] = { fg = "#8B7EC8" },
  ["CmpItemKindTypeParameter"] = { fg = "#D14D41" },
  ["CmpItemKindUnit"] = { fg = "#D0A215" },
  ["CmpItemKindValue"] = { fg = "#3AA99F" },
  ["CmpItemKindVariable"] = { fg = "#D0A215" },
  ["CmpPmenu"] = { bg = "#100F0F" },
  ["CmpSel"] = { bold = true, link = "PmenuSel" },
  ["Conditional"] = { fg = "#D0A215" },
  ["Constant"] = { fg = "#DA702C" },
  ["Define"] = { fg = "#D0A215", sp = "none" },
  ["Delimiter"] = { fg = "#519ABA" },
  ["DevIconDart"] = { fg = "#3AA99F" },
  ["DevIconDockerfile"] = { fg = "#3AA99F" },
  ["DevIconJSX"] = { fg = "#4385BE" },
  ["DevIconJava"] = { fg = "#DA702C" },
  ["DevIconMd"] = { fg = "#4385BE" },
  ["DevIconSvelte"] = { fg = "#D14D41" },
  ["DevIconTSX"] = { fg = "#4385BE" },
  ["DevIconZig"] = { fg = "#DA702C" },
  ["DevIconc"] = { fg = "#4385BE" },
  ["DevIconcss"] = { fg = "#4385BE" },
  ["DevIcondeb"] = { fg = "#3AA99F" },
  ["DevIconhtml"] = { fg = "#d36da1" },
  ["DevIconjpeg"] = { fg = "#7f70c2" },
  ["DevIconjpg"] = { fg = "#7f70c2" },
  ["DevIconjs"] = { fg = "#eabb2b" },
  ["DevIconkt"] = { fg = "#DA702C" },
  ["DevIconlock"] = { fg = "#D14D41" },
  ["DevIconlua"] = { fg = "#4385BE" },
  ["DevIconmp3"] = { fg = "#CECDC3" },
  ["DevIconmp4"] = { fg = "#CECDC3" },
  ["DevIconout"] = { fg = "#CECDC3" },
  ["DevIconpng"] = { fg = "#7f70c2" },
  ["DevIconpy"] = { fg = "#3AA99F" },
  ["DevIconrb"] = { fg = "#CE5D97" },
  ["DevIconrpm"] = { fg = "#DA702C" },
  ["DevIcontoml"] = { fg = "#4385BE" },
  ["DevIconts"] = { fg = "#519ABA" },
  ["DevIconttf"] = { fg = "#CECDC3" },
  ["DevIconvue"] = { fg = "#7e9f0e" },
  ["DevIconwoff"] = { fg = "#CECDC3" },
  ["DevIconwoff2"] = { fg = "#CECDC3" },
  ["DevIconxz"] = { fg = "#eabb2b" },
  ["DevIconzip"] = { fg = "#eabb2b" },
  ["DiagnosticError"] = { fg = "#D14D41" },
  ["DiagnosticHint"] = { fg = "#8B7EC8" },
  ["DiagnosticInfo"] = { fg = "#879A39" },
  ["DiagnosticWarn"] = { fg = "#D0A215" },
  ["DiffAdd"] = { fg = "#879A39", bg = "#1b1c13" },
  ["DiffAdded"] = { fg = "#879A39", bg = "#1b1c13" },
  ["DiffChange"] = { fg = "#6a6363", bg = "#191717" },
  ["DiffChangeDelete"] = { fg = "#D14D41", bg = "#231514" },
  ["DiffDelete"] = { fg = "#D14D41", bg = "#231514" },
  ["DiffModified"] = { fg = "#DA702C", bg = "#241811" },
  ["DiffRemoved"] = { fg = "#D14D41", bg = "#231514" },
  ["DiffText"] = { fg = "#CECDC3", bg = "#1c1b1b" },
  ["Float"] = { fg = "#DA702C" },
  ["Function"] = { fg = "#4385BE" },
  ["IblChar"] = { fg = "#292626" },
  ["IblScopeChar"] = { fg = "#393636" },
  ["Identifier"] = { fg = "#D14D41", sp = "none" },
  ["Include"] = { fg = "#D0A215" },
  ["Keyword"] = { fg = "#3AA99F" },
  ["Label"] = { fg = "#8B7EC8" },
  ["LspInlayHint"] = { fg = "#6a6363", bg = "#1c1b1b" },
  ["LspReferenceRead"] = { bg = "#373434" },
  ["LspReferenceText"] = { bg = "#373434" },
  ["LspReferenceWrite"] = { bg = "#373434" },
  ["LspSignatureActiveParameter"] = { fg = "#100F0F", bg = "#879A39" },
  ["MasonHeader"] = { fg = "#100F0F", bg = "#D14D41" },
  ["MasonHeaderSecondary"] = { link = "MasonHighlightBlock" },
  ["MasonHighlight"] = { fg = "#4385BE" },
  ["MasonHighlightBlock"] = { fg = "#100F0F", bg = "#879A39" },
  ["MasonHighlightBlockBold"] = { link = "MasonHighlightBlock" },
  ["MasonMuted"] = { fg = "#6a6363" },
  ["MasonMutedBlock"] = { fg = "#6a6363", bg = "#292626" },
  ["Number"] = { fg = "#DA702C" },
  ["NvimTreeCursorLine"] = { bg = "#100F0F" },
  ["NvimTreeDiagnosticErrorFileHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticErrorFolderHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticHintFileHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticHintFolderHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticInfoFileHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticInfoFolderHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticWarnFileHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeDiagnosticWarnFolderHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeEmptyFolderName"] = { fg = "#4385BE" },
  ["NvimTreeEndOfBuffer"] = { fg = "#171616" },
  ["NvimTreeFolderArrowClosed"] = { fg = "#555050" },
  ["NvimTreeFolderArrowOpen"] = { fg = "#4385BE" },
  ["NvimTreeFolderIcon"] = { fg = "#4385BE" },
  ["NvimTreeFolderName"] = { fg = "#4385BE" },
  ["NvimTreeGitDeleted"] = { fg = "#D14D41" },
  ["NvimTreeGitDirty"] = { fg = "#D14D41" },
  ["NvimTreeGitIgnored"] = { fg = "#6a6363" },
  ["NvimTreeGitNew"] = { fg = "#D0A215" },
  ["NvimTreeIndentMarker"] = { fg = "#232121" },
  ["NvimTreeNormal"] = { bg = "#171616" },
  ["NvimTreeNormalNC"] = { bg = "#171616" },
  ["NvimTreeOpenedFolderName"] = { fg = "#4385BE" },
  ["NvimTreeRootFolder"] = { fg = "#D14D41", bold = true },
  ["NvimTreeSpecialFile"] = { fg = "#D0A215", bold = true },
  ["NvimTreeWinSeparator"] = { fg = "#171616", bg = "#171616" },
  ["NvimTreeWindowPicker"] = { fg = "#D14D41", bg = "#1c1b1b" },
  ["Operator"] = { fg = "#CECDC3", sp = "none" },
  ["PreProc"] = { fg = "#8B7EC8" },
  ["Repeat"] = { fg = "#8B7EC8" },
  ["Special"] = { fg = "#3AA99F" },
  ["SpecialChar"] = { fg = "#519ABA" },
  ["Statement"] = { fg = "#D14D41" },
  ["StorageClass"] = { fg = "#8B7EC8" },
  ["String"] = { fg = "#879A39" },
  ["Structure"] = { fg = "#D0A215" },
  ["TBTabTitle"] = { fg = "#100F0F", bg = "#4385BE" },
  ["Tabline"] = { bg = "#1c1b1b" },
  ["Tag"] = { fg = "#4385BE" },
  ["TbBufOff"] = { fg = "#6a6363", bg = "#1c1b1b" },
  ["TbBufOffClose"] = { fg = "#6a6363", bg = "#1c1b1b" },
  ["TbBufOffModified"] = { fg = "#D14D41", bg = "#1c1b1b" },
  ["TbBufOn"] = { fg = "#CECDC3", bg = "#100F0F" },
  ["TbBufOnClose"] = { fg = "#D14D41", bg = "#100F0F" },
  ["TbBufOnModified"] = { fg = "#879A39", bg = "#100F0F" },
  ["TbCloseAllBufsBtn"] = { fg = "#100F0F", bg = "#D14D41", bold = true },
  ["TbFill"] = { bg = "#1c1b1b" },
  ["TbTabCloseBtn"] = { fg = "#100F0F", bg = "#4385BE" },
  ["TbTabNewBtn"] = { fg = "#CECDC3", bg = "#353232" },
  ["TbTabOff"] = { fg = "#CECDC3", bg = "#1c1b1b" },
  ["TbTabOn"] = { fg = "#D14D41", bg = "#100F0F" },
  ["TbThemeToggleBtn"] = { fg = "#CECDC3", bg = "#373434", bold = true },
  ["TelescopeBorder"] = { fg = "#373434" },
  ["TelescopeMatching"] = { fg = "#4385BE", bg = "#292626" },
  ["TelescopeNormal"] = { bg = "none" },
  ["TelescopePreviewTitle"] = { fg = "#100F0F", bg = "#4385BE" },
  ["TelescopePromptBorder"] = { fg = "#373434" },
  ["TelescopePromptNormal"] = { bg = "none" },
  ["TelescopePromptPrefix"] = { fg = "#D14D41", bg = "none" },
  ["TelescopePromptTitle"] = { fg = "#100F0F", bg = "#D14D41" },
  ["TelescopeResultsDiffAdd"] = { fg = "#879A39" },
  ["TelescopeResultsDiffChange"] = { fg = "#D0A215" },
  ["TelescopeResultsDiffDelete"] = { fg = "#D14D41" },
  ["TelescopeResultsTitle"] = { fg = "#100F0F", bg = "#879A39" },
  ["TelescopeSelection"] = { fg = "#CECDC3", bg = "#1c1b1b" },
  ["Todo"] = { fg = "#8B7EC8", bg = "#1c1b1b" },
  ["Type"] = { fg = "#8B7EC8", sp = "none" },
  ["Typedef"] = { fg = "#8B7EC8" },
  ["Variable"] = { fg = "#CECDC3" },
  ["WhichKey"] = { fg = "#4385BE" },
  ["WhichKeyDesc"] = { fg = "#D14D41" },
  ["WhichKeyGroup"] = { fg = "#879A39" },
  ["WhichKeySeparator"] = { fg = "#6a6363" },
  ["WhichKeyValue"] = { fg = "#879A39" },
  ["diffNewFile"] = { fg = "#4385BE" },
  ["diffOldFile"] = { fg = "#d36da1" },
  ["gitcommitBranch"] = { fg = "#DA702C", bold = true },
  ["gitcommitComment"] = { fg = "#393636" },
  ["gitcommitDiscarded"] = { fg = "#393636" },
  ["gitcommitDiscardedFile"] = { fg = "#D14D41", bold = true },
  ["gitcommitDiscardedType"] = { fg = "#4385BE" },
  ["gitcommitHeader"] = { fg = "#D0A215" },
  ["gitcommitOverflow"] = { fg = "#D14D41" },
  ["gitcommitSelected"] = { fg = "#393636" },
  ["gitcommitSelectedFile"] = { fg = "#879A39", bold = true },
  ["gitcommitSelectedType"] = { fg = "#4385BE" },
  ["gitcommitSummary"] = { fg = "#879A39" },
  ["gitcommitUnmergedFile"] = { fg = "#D14D41", bold = true },
  ["gitcommitUnmergedType"] = { fg = "#4385BE" },
  ["gitcommitUntracked"] = { fg = "#393636" },
  ["gitcommitUntrackedFile"] = { fg = "#8B7EC8" },
}

function M.apply()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.background = M.background
  vim.g.colors_name = M.name
  for group, hl in pairs(M.highlights) do
    vim.api.nvim_set_hl(0, group, hl)
  end
  vim.api.nvim_exec_autocmds("ColorScheme", { pattern = M.name })
end

return M
