return {
  { name = "nvchad-aquarium", label = "NvChad Aquarium", module = "aquarium", source = "aquarium" },
  { name = "nvchad-ashes", label = "NvChad Ashes", module = "ashes", source = "ashes" },
  { name = "nvchad-aylin", label = "NvChad Aylin", module = "aylin", source = "aylin" },
  { name = "nvchad-ayu_dark", label = "NvChad Ayu Dark", module = "ayu_dark", source = "ayu_dark" },
  { name = "nvchad-ayu_light", label = "NvChad Ayu Light", module = "ayu_light", source = "ayu_light" },
  { name = "nvchad-bearded-arc", label = "NvChad Bearded Arc", module = "bearded_arc", source = "bearded-arc" },
  { name = "nvchad-blossom_light", label = "NvChad Blossom Light", module = "blossom_light", source = "blossom_light" },
  { name = "nvchad-carbonfox", label = "NvChad Carbonfox", module = "carbonfox", source = "carbonfox" },
  { name = "nvchad-catppuccin", label = "NvChad Catppuccin", module = "catppuccin", source = "catppuccin" },
  { name = "nvchad-catppuccin-latte", label = "NvChad Catppuccin Latte", module = "catppuccin_latte", source = "catppuccin-latte" },
  { name = "nvchad-chadracula", label = "NvChad Chadracula", module = "chadracula", source = "chadracula" },
  { name = "nvchad-chadracula-evondev", label = "NvChad Chadracula Evondev", module = "chadracula_evondev", source = "chadracula-evondev" },
  { name = "nvchad-chadtain", label = "NvChad Chadtain", module = "chadtain", source = "chadtain" },
  { name = "nvchad-chocolate", label = "NvChad Chocolate", module = "chocolate", source = "chocolate" },
  { name = "nvchad-darcula-dark", label = "NvChad Darcula Dark", module = "darcula_dark", source = "darcula-dark" },
  { name = "nvchad-dark_horizon", label = "NvChad Dark Horizon", module = "dark_horizon", source = "dark_horizon" },
  { name = "nvchad-decay", label = "NvChad Decay", module = "decay", source = "decay" },
  { name = "nvchad-default-dark", label = "NvChad Default Dark", module = "default_dark", source = "default-dark" },
  { name = "nvchad-default-light", label = "NvChad Default Light", module = "default_light", source = "default-light" },
  { name = "nvchad-doomchad", label = "NvChad Doomchad", module = "doomchad", source = "doomchad" },
  { name = "nvchad-eldritch", label = "NvChad Eldritch", module = "eldritch", source = "eldritch" },
  { name = "nvchad-embark", label = "NvChad Embark", module = "embark", source = "embark" },
  { name = "nvchad-everblush", label = "NvChad Everblush", module = "everblush", source = "everblush" },
  { name = "nvchad-everforest", label = "NvChad Everforest", module = "everforest", source = "everforest" },
  { name = "nvchad-everforest_light", label = "NvChad Everforest Light", module = "everforest_light", source = "everforest_light" },
  { name = "nvchad-falcon", label = "NvChad Falcon", module = "falcon", source = "falcon" },
  { name = "nvchad-flex-light", label = "NvChad Flex Light", module = "flex_light", source = "flex-light" },
  { name = "nvchad-flexoki", label = "NvChad Flexoki", module = "flexoki", source = "flexoki" },
  { name = "nvchad-flexoki-light", label = "NvChad Flexoki Light", module = "flexoki_light", source = "flexoki-light" },
  { name = "nvchad-flouromachine", label = "NvChad Flouromachine", module = "flouromachine", source = "flouromachine" },
  { name = "nvchad-gatekeeper", label = "NvChad Gatekeeper", module = "gatekeeper", source = "gatekeeper" },
  { name = "nvchad-github_dark", label = "NvChad Github Dark", module = "github_dark", source = "github_dark" },
  { name = "nvchad-github_light", label = "NvChad Github Light", module = "github_light", source = "github_light" },
  { name = "nvchad-gruvbox", label = "NvChad Gruvbox", module = "gruvbox", source = "gruvbox" },
  { name = "nvchad-gruvbox_light", label = "NvChad Gruvbox Light", module = "gruvbox_light", source = "gruvbox_light" },
  { name = "nvchad-gruvchad", label = "NvChad Gruvchad", module = "gruvchad", source = "gruvchad" },
  { name = "nvchad-hiberbee", label = "NvChad Hiberbee", module = "hiberbee", source = "hiberbee" },
  { name = "nvchad-horizon", label = "NvChad Horizon", module = "horizon", source = "horizon" },
  { name = "nvchad-jabuti", label = "NvChad Jabuti", module = "jabuti", source = "jabuti" },
  { name = "nvchad-jellybeans", label = "NvChad Jellybeans", module = "jellybeans", source = "jellybeans" },
  { name = "nvchad-kanagawa", label = "NvChad Kanagawa", module = "kanagawa", source = "kanagawa" },
  { name = "nvchad-kanagawa-dragon", label = "NvChad Kanagawa Dragon", module = "kanagawa_dragon", source = "kanagawa-dragon" },
  { name = "nvchad-material-darker", label = "NvChad Material Darker", module = "material_darker", source = "material-darker" },
  { name = "nvchad-material-deep-ocean", label = "NvChad Material Deep Ocean", module = "material_deep_ocean", source = "material-deep-ocean" },
  { name = "nvchad-material-lighter", label = "NvChad Material Lighter", module = "material_lighter", source = "material-lighter" },
  { name = "nvchad-melange", label = "NvChad Melange", module = "melange", source = "melange" },
  { name = "nvchad-midnight_breeze", label = "NvChad Midnight Breeze", module = "midnight_breeze", source = "midnight_breeze" },
  { name = "nvchad-mito-laser", label = "NvChad Mito Laser", module = "mito_laser", source = "mito-laser" },
  { name = "nvchad-monekai", label = "NvChad Monekai", module = "monekai", source = "monekai" },
  { name = "nvchad-monochrome", label = "NvChad Monochrome", module = "monochrome", source = "monochrome" },
  { name = "nvchad-mountain", label = "NvChad Mountain", module = "mountain", source = "mountain" },
  { name = "nvchad-nano-light", label = "NvChad Nano Light", module = "nano_light", source = "nano-light" },
  { name = "nvchad-neofusion", label = "NvChad Neofusion", module = "neofusion", source = "neofusion" },
  { name = "nvchad-nightfox", label = "NvChad Nightfox", module = "nightfox", source = "nightfox" },
  { name = "nvchad-nightlamp", label = "NvChad Nightlamp", module = "nightlamp", source = "nightlamp" },
  { name = "nvchad-nightowl", label = "NvChad Nightowl", module = "nightowl", source = "nightowl" },
  { name = "nvchad-nord", label = "NvChad Nord", module = "nord", source = "nord" },
  { name = "nvchad-obsidian-ember", label = "NvChad Obsidian Ember", module = "obsidian_ember", source = "obsidian-ember" },
  { name = "nvchad-oceanic-light", label = "NvChad Oceanic Light", module = "oceanic_light", source = "oceanic-light" },
  { name = "nvchad-oceanic-next", label = "NvChad Oceanic Next", module = "oceanic_next", source = "oceanic-next" },
  { name = "nvchad-one_light", label = "NvChad One Light", module = "one_light", source = "one_light" },
  { name = "nvchad-onedark", label = "NvChad Onedark", module = "onedark", source = "onedark" },
  { name = "nvchad-onenord", label = "NvChad Onenord", module = "onenord", source = "onenord" },
  { name = "nvchad-onenord_light", label = "NvChad Onenord Light", module = "onenord_light", source = "onenord_light" },
  { name = "nvchad-oxocarbon", label = "NvChad Oxocarbon", module = "oxocarbon", source = "oxocarbon" },
  { name = "nvchad-palenight", label = "NvChad Palenight", module = "palenight", source = "palenight" },
  { name = "nvchad-pastelDark", label = "NvChad PastelDark", module = "pastelDark", source = "pastelDark" },
  { name = "nvchad-pastelbeans", label = "NvChad Pastelbeans", module = "pastelbeans", source = "pastelbeans" },
  { name = "nvchad-penumbra_dark", label = "NvChad Penumbra Dark", module = "penumbra_dark", source = "penumbra_dark" },
  { name = "nvchad-penumbra_light", label = "NvChad Penumbra Light", module = "penumbra_light", source = "penumbra_light" },
  { name = "nvchad-poimandres", label = "NvChad Poimandres", module = "poimandres", source = "poimandres" },
  { name = "nvchad-radium", label = "NvChad Radium", module = "radium", source = "radium" },
  { name = "nvchad-rosepine", label = "NvChad Rosepine", module = "rosepine", source = "rosepine" },
  { name = "nvchad-rosepine-dawn", label = "NvChad Rosepine Dawn", module = "rosepine_dawn", source = "rosepine-dawn" },
  { name = "nvchad-rxyhn", label = "NvChad Rxyhn", module = "rxyhn", source = "rxyhn" },
  { name = "nvchad-scaryforest", label = "NvChad Scaryforest", module = "scaryforest", source = "scaryforest" },
  { name = "nvchad-seoul256_dark", label = "NvChad Seoul256 Dark", module = "seoul256_dark", source = "seoul256_dark" },
  { name = "nvchad-seoul256_light", label = "NvChad Seoul256 Light", module = "seoul256_light", source = "seoul256_light" },
  { name = "nvchad-solarized_dark", label = "NvChad Solarized Dark", module = "solarized_dark", source = "solarized_dark" },
  { name = "nvchad-solarized_light", label = "NvChad Solarized Light", module = "solarized_light", source = "solarized_light" },
  { name = "nvchad-solarized_osaka", label = "NvChad Solarized Osaka", module = "solarized_osaka", source = "solarized_osaka" },
  { name = "nvchad-starlight", label = "NvChad Starlight", module = "starlight", source = "starlight" },
  { name = "nvchad-sunrise_breeze", label = "NvChad Sunrise Breeze", module = "sunrise_breeze", source = "sunrise_breeze" },
  { name = "nvchad-sweetpastel", label = "NvChad Sweetpastel", module = "sweetpastel", source = "sweetpastel" },
  { name = "nvchad-tokyodark", label = "NvChad Tokyodark", module = "tokyodark", source = "tokyodark" },
  { name = "nvchad-tokyonight", label = "NvChad Tokyonight", module = "tokyonight", source = "tokyonight" },
  { name = "nvchad-tomorrow_night", label = "NvChad Tomorrow Night", module = "tomorrow_night", source = "tomorrow_night" },
  { name = "nvchad-tundra", label = "NvChad Tundra", module = "tundra", source = "tundra" },
  { name = "nvchad-vesper", label = "NvChad Vesper", module = "vesper", source = "vesper" },
  { name = "nvchad-vscode_dark", label = "NvChad Vscode Dark", module = "vscode_dark", source = "vscode_dark" },
  { name = "nvchad-vscode_light", label = "NvChad Vscode Light", module = "vscode_light", source = "vscode_light" },
  { name = "nvchad-wombat", label = "NvChad Wombat", module = "wombat", source = "wombat" },
  { name = "nvchad-yoru", label = "NvChad Yoru", module = "yoru", source = "yoru" },
  { name = "nvchad-zenburn", label = "NvChad Zenburn", module = "zenburn", source = "zenburn" },
}
