local M = {}

M.name = "nvchad-solarized_dark"
M.label = "NvChad Solarized Dark"
M.source = "solarized_dark"
M.background = "dark"

M.highlights = {
  ["@annotation"] = { fg = "#d33682" },
  ["@attribute"] = { fg = "#b58900" },
  ["@character"] = { fg = "#dc322f" },
  ["@comment"] = { fg = "#325d68" },
  ["@comment.danger"] = { fg = "#06313c", bg = "#dc322f" },
  ["@comment.note"] = { fg = "#002b36", bg = "#268bd2" },
  ["@comment.todo"] = { fg = "#28535e", bg = "#abb2bf" },
  ["@comment.warning"] = { fg = "#06313c", bg = "#cb4b16" },
  ["@constant"] = { fg = "#cb4b16" },
  ["@constant.builtin"] = { fg = "#cb4b16" },
  ["@constant.macro"] = { fg = "#dc322f" },
  ["@constructor"] = { fg = "#2aa198" },
  ["@definition"] = { sp = "#1b4651", underline = true },
  ["@diff.delta"] = { fg = "#446f7a" },
  ["@diff.minus"] = { fg = "#dc322f" },
  ["@diff.plus"] = { fg = "#859900" },
  ["@error"] = { fg = "#dc322f" },
  ["@function"] = { fg = "#268bd2" },
  ["@function.builtin"] = { fg = "#268bd2" },
  ["@function.call"] = { fg = "#268bd2" },
  ["@function.macro"] = { fg = "#dc322f" },
  ["@function.method"] = { fg = "#268bd2" },
  ["@function.method.call"] = { fg = "#268bd2" },
  ["@ibl.scope.underline.1"] = { bg = "#06313c" },
  ["@ibl.scope.underline.2"] = { bg = "#06313c" },
  ["@ibl.scope.underline.3"] = { bg = "#06313c" },
  ["@ibl.scope.underline.4"] = { bg = "#06313c" },
  ["@ibl.scope.underline.5"] = { bg = "#06313c" },
  ["@ibl.scope.underline.6"] = { bg = "#06313c" },
  ["@ibl.scope.underline.7"] = { bg = "#06313c" },
  ["@keyword"] = { fg = "#6c71c4" },
  ["@keyword.conditional"] = { fg = "#6c71c4" },
  ["@keyword.conditional.ternary"] = { fg = "#6c71c4" },
  ["@keyword.directive"] = { fg = "#b58900" },
  ["@keyword.directive.define"] = { fg = "#6c71c4" },
  ["@keyword.exception"] = { fg = "#dc322f" },
  ["@keyword.function"] = { fg = "#6c71c4" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.operator"] = { fg = "#6c71c4" },
  ["@keyword.repeat"] = { fg = "#b58900" },
  ["@keyword.return"] = { fg = "#6c71c4" },
  ["@keyword.storage"] = { fg = "#b58900" },
  ["@markup.heading"] = { fg = "#268bd2" },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = "#dc322f" },
  ["@markup.link.label"] = { fg = "#2aa198" },
  ["@markup.link.url"] = { fg = "#cb4b16", underline = true },
  ["@markup.list"] = { fg = "#dc322f" },
  ["@markup.quote"] = { bg = "#06313c" },
  ["@markup.raw"] = { fg = "#cb4b16" },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@module"] = { fg = "#dc322f" },
  ["@number"] = { fg = "#cb4b16" },
  ["@number.float"] = { fg = "#cb4b16" },
  ["@operator"] = { fg = "#93a1a1" },
  ["@property"] = { fg = "#dc322f" },
  ["@punctuation.bracket"] = { fg = "#d33682" },
  ["@punctuation.delimiter"] = { fg = "#d33682" },
  ["@reference"] = { fg = "#93a1a1" },
  ["@scope"] = { bold = true },
  ["@string"] = { fg = "#859900" },
  ["@string.escape"] = { fg = "#2aa198" },
  ["@string.regex"] = { fg = "#2aa198" },
  ["@symbol"] = { fg = "#859900" },
  ["@tag"] = { fg = "#b58900" },
  ["@tag.attribute"] = { fg = "#dc322f" },
  ["@tag.delimiter"] = { fg = "#d33682" },
  ["@text"] = { fg = "#93a1a1" },
  ["@text.emphasis"] = { fg = "#cb4b16" },
  ["@text.strike"] = { fg = "#d33682", strikethrough = true },
  ["@type.builtin"] = { fg = "#b58900" },
  ["@variable"] = { fg = "#93a1a1" },
  ["@variable.builtin"] = { fg = "#cb4b16" },
  ["@variable.member"] = { fg = "#dc322f" },
  ["@variable.member.key"] = { fg = "#dc322f" },
  ["@variable.parameter"] = { fg = "#dc322f" },
  ["BlinkCmpDoc"] = { bg = "#002b36" },
  ["BlinkCmpDocBorder"] = { fg = "#325d68" },
  ["BlinkCmpDocCursorLine"] = { bg = "#0a3540" },
  ["BlinkCmpDocSeparator"] = { fg = "#28535e" },
  ["BlinkCmpGhostText"] = { fg = "#325d68" },
  ["BlinkCmpKindClass"] = { fg = "#519ABA" },
  ["BlinkCmpKindCodeium"] = { fg = "#b2c62d" },
  ["BlinkCmpKindColor"] = { fg = "#abb2bf" },
  ["BlinkCmpKindConstant"] = { fg = "#cb4b16" },
  ["BlinkCmpKindConstructor"] = { fg = "#268bd2" },
  ["BlinkCmpKindCopilot"] = { fg = "#859900" },
  ["BlinkCmpKindEnum"] = { fg = "#268bd2" },
  ["BlinkCmpKindEnumMember"] = { fg = "#6c71c4" },
  ["BlinkCmpKindEvent"] = { fg = "#b58900" },
  ["BlinkCmpKindField"] = { fg = "#dc322f" },
  ["BlinkCmpKindFile"] = { fg = "#fdf6e3" },
  ["BlinkCmpKindFolder"] = { fg = "#fdf6e3" },
  ["BlinkCmpKindFunction"] = { fg = "#268bd2" },
  ["BlinkCmpKindIdentifier"] = { fg = "#dc322f" },
  ["BlinkCmpKindInterface"] = { fg = "#859900" },
  ["BlinkCmpKindKeyword"] = { fg = "#fdf6e3" },
  ["BlinkCmpKindMethod"] = { fg = "#268bd2" },
  ["BlinkCmpKindModule"] = { fg = "#b58900" },
  ["BlinkCmpKindOperator"] = { fg = "#93a1a1" },
  ["BlinkCmpKindProperty"] = { fg = "#dc322f" },
  ["BlinkCmpKindReference"] = { fg = "#93a1a1" },
  ["BlinkCmpKindSnippet"] = { fg = "#dc322f" },
  ["BlinkCmpKindStruct"] = { fg = "#6c71c4" },
  ["BlinkCmpKindStructure"] = { fg = "#6c71c4" },
  ["BlinkCmpKindSuperMaven"] = { fg = "#b58900" },
  ["BlinkCmpKindTabNine"] = { fg = "#eb413e" },
  ["BlinkCmpKindText"] = { fg = "#859900" },
  ["BlinkCmpKindType"] = { fg = "#b58900" },
  ["BlinkCmpKindTypeParameter"] = { fg = "#dc322f" },
  ["BlinkCmpKindUnit"] = { fg = "#6c71c4" },
  ["BlinkCmpKindValue"] = { fg = "#2aa198" },
  ["BlinkCmpKindVariable"] = { fg = "#6c71c4" },
  ["BlinkCmpLabel"] = { fg = "#abb2bf" },
  ["BlinkCmpLabelDeprecated"] = { fg = "#dc322f", strikethrough = true },
  ["BlinkCmpLabelDescription"] = { fg = "#446f7a" },
  ["BlinkCmpLabelDetail"] = { fg = "#446f7a" },
  ["BlinkCmpLabelMatch"] = { fg = "#268bd2", bold = true },
  ["BlinkCmpMenu"] = { bg = "#002b36" },
  ["BlinkCmpMenuBorder"] = { fg = "#325d68" },
  ["BlinkCmpMenuSelection"] = { bold = true, link = "PmenuSel" },
  ["BlinkCmpScrollBarGutter"] = { bg = "#06313c" },
  ["BlinkCmpScrollBarThumb"] = { bg = "#28535e" },
  ["BlinkCmpSignatureHelp"] = { bg = "#002b36" },
  ["BlinkCmpSignatureHelpActiveParameter"] = { fg = "#268bd2", bold = true },
  ["BlinkCmpSignatureHelpBorder"] = { fg = "#325d68" },
  ["BlinkCmpSource"] = { fg = "#325d68" },
  ["Boolean"] = { fg = "#cb4b16" },
  ["Character"] = { fg = "#dc322f" },
  ["CmpBorder"] = { fg = "#325d68" },
  ["CmpDoc"] = { bg = "#002b36" },
  ["CmpDocBorder"] = { fg = "#325d68" },
  ["CmpItemAbbr"] = { fg = "#abb2bf" },
  ["CmpItemAbbrMatch"] = { fg = "#268bd2", bold = true },
  ["CmpItemKindClass"] = { fg = "#519ABA" },
  ["CmpItemKindCodeium"] = { fg = "#b2c62d" },
  ["CmpItemKindColor"] = { fg = "#abb2bf" },
  ["CmpItemKindConstant"] = { fg = "#cb4b16" },
  ["CmpItemKindConstructor"] = { fg = "#268bd2" },
  ["CmpItemKindCopilot"] = { fg = "#859900" },
  ["CmpItemKindEnum"] = { fg = "#268bd2" },
  ["CmpItemKindEnumMember"] = { fg = "#6c71c4" },
  ["CmpItemKindEvent"] = { fg = "#b58900" },
  ["CmpItemKindField"] = { fg = "#dc322f" },
  ["CmpItemKindFile"] = { fg = "#fdf6e3" },
  ["CmpItemKindFolder"] = { fg = "#fdf6e3" },
  ["CmpItemKindFunction"] = { fg = "#268bd2" },
  ["CmpItemKindIdentifier"] = { fg = "#dc322f" },
  ["CmpItemKindInterface"] = { fg = "#859900" },
  ["CmpItemKindKeyword"] = { fg = "#fdf6e3" },
  ["CmpItemKindMethod"] = { fg = "#268bd2" },
  ["CmpItemKindModule"] = { fg = "#b58900" },
  ["CmpItemKindOperator"] = { fg = "#93a1a1" },
  ["CmpItemKindProperty"] = { fg = "#dc322f" },
  ["CmpItemKindReference"] = { fg = "#93a1a1" },
  ["CmpItemKindSnippet"] = { fg = "#dc322f" },
  ["CmpItemKindStruct"] = { fg = "#6c71c4" },
  ["CmpItemKindStructure"] = { fg = "#6c71c4" },
  ["CmpItemKindSuperMaven"] = { fg = "#b58900" },
  ["CmpItemKindTabNine"] = { fg = "#eb413e" },
  ["CmpItemKindText"] = { fg = "#859900" },
  ["CmpItemKindType"] = { fg = "#b58900" },
  ["CmpItemKindTypeParameter"] = { fg = "#dc322f" },
  ["CmpItemKindUnit"] = { fg = "#6c71c4" },
  ["CmpItemKindValue"] = { fg = "#2aa198" },
  ["CmpItemKindVariable"] = { fg = "#6c71c4" },
  ["CmpPmenu"] = { bg = "#002b36" },
  ["CmpSel"] = { bold = true, link = "PmenuSel" },
  ["Conditional"] = { fg = "#6c71c4" },
  ["Constant"] = { fg = "#cb4b16" },
  ["Define"] = { fg = "#6c71c4", sp = "none" },
  ["Delimiter"] = { fg = "#d33682" },
  ["DevIconDart"] = { fg = "#2aa198" },
  ["DevIconDockerfile"] = { fg = "#2aa198" },
  ["DevIconJSX"] = { fg = "#268bd2" },
  ["DevIconJava"] = { fg = "#cb4b16" },
  ["DevIconMd"] = { fg = "#268bd2" },
  ["DevIconSvelte"] = { fg = "#dc322f" },
  ["DevIconTSX"] = { fg = "#268bd2" },
  ["DevIconZig"] = { fg = "#cb4b16" },
  ["DevIconc"] = { fg = "#268bd2" },
  ["DevIconcss"] = { fg = "#268bd2" },
  ["DevIcondeb"] = { fg = "#2aa198" },
  ["DevIconhtml"] = { fg = "#eb413e" },
  ["DevIconjpeg"] = { fg = "#5d62b5" },
  ["DevIconjpg"] = { fg = "#5d62b5" },
  ["DevIconjs"] = { fg = "#c4980f" },
  ["DevIconkt"] = { fg = "#cb4b16" },
  ["DevIconlock"] = { fg = "#dc322f" },
  ["DevIconlua"] = { fg = "#268bd2" },
  ["DevIconmp3"] = { fg = "#abb2bf" },
  ["DevIconmp4"] = { fg = "#abb2bf" },
  ["DevIconout"] = { fg = "#abb2bf" },
  ["DevIconpng"] = { fg = "#5d62b5" },
  ["DevIconpy"] = { fg = "#2aa198" },
  ["DevIconrb"] = { fg = "#d33682" },
  ["DevIconrpm"] = { fg = "#cb4b16" },
  ["DevIcontoml"] = { fg = "#268bd2" },
  ["DevIconts"] = { fg = "#519ABA" },
  ["DevIconttf"] = { fg = "#abb2bf" },
  ["DevIconvue"] = { fg = "#b2c62d" },
  ["DevIconwoff"] = { fg = "#abb2bf" },
  ["DevIconwoff2"] = { fg = "#abb2bf" },
  ["DevIconxz"] = { fg = "#c4980f" },
  ["DevIconzip"] = { fg = "#c4980f" },
  ["DiagnosticError"] = { fg = "#dc322f" },
  ["DiagnosticHint"] = { fg = "#6c71c4" },
  ["DiagnosticInfo"] = { fg = "#859900" },
  ["DiagnosticWarn"] = { fg = "#b58900" },
  ["DiffAdd"] = { fg = "#859900", bg = "#0d3630" },
  ["DiffAdded"] = { fg = "#859900", bg = "#0d3630" },
  ["DiffChange"] = { fg = "#446f7a", bg = "#06313c" },
  ["DiffChangeDelete"] = { fg = "#dc322f", bg = "#152b35" },
  ["DiffDelete"] = { fg = "#dc322f", bg = "#152b35" },
  ["DiffModified"] = { fg = "#cb4b16", bg = "#142e32" },
  ["DiffRemoved"] = { fg = "#dc322f", bg = "#152b35" },
  ["DiffText"] = { fg = "#abb2bf", bg = "#06313c" },
  ["Float"] = { fg = "#cb4b16" },
  ["Function"] = { fg = "#268bd2" },
  ["IblChar"] = { fg = "#0f3a45" },
  ["IblScopeChar"] = { fg = "#28535e" },
  ["Identifier"] = { fg = "#dc322f", sp = "none" },
  ["Include"] = { fg = "#268bd2" },
  ["Keyword"] = { fg = "#6c71c4" },
  ["Label"] = { fg = "#b58900" },
  ["LspInlayHint"] = { fg = "#446f7a", bg = "#05303c" },
  ["LspReferenceRead"] = { bg = "#1b4651" },
  ["LspReferenceText"] = { bg = "#1b4651" },
  ["LspReferenceWrite"] = { bg = "#1b4651" },
  ["LspSignatureActiveParameter"] = { fg = "#002b36", bg = "#859900" },
  ["MasonHeader"] = { fg = "#002b36", bg = "#dc322f" },
  ["MasonHeaderSecondary"] = { link = "MasonHighlightBlock" },
  ["MasonHighlight"] = { fg = "#268bd2" },
  ["MasonHighlightBlock"] = { fg = "#002b36", bg = "#859900" },
  ["MasonHighlightBlockBold"] = { link = "MasonHighlightBlock" },
  ["MasonMuted"] = { fg = "#446f7a" },
  ["MasonMutedBlock"] = { fg = "#446f7a", bg = "#0a3540" },
  ["Number"] = { fg = "#cb4b16" },
  ["NvimTreeCursorLine"] = { bg = "#002b36" },
  ["NvimTreeDiagnosticErrorFileHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticErrorFolderHL"] = { link = "DiagnosticError" },
  ["NvimTreeDiagnosticHintFileHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticHintFolderHL"] = { link = "DiagnosticHint" },
  ["NvimTreeDiagnosticInfoFileHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticInfoFolderHL"] = { link = "DiagnosticNormal" },
  ["NvimTreeDiagnosticWarnFileHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeDiagnosticWarnFolderHL"] = { link = "DiagnosticWarn" },
  ["NvimTreeEmptyFolderName"] = { fg = "#268bd2" },
  ["NvimTreeEndOfBuffer"] = { fg = "#002530" },
  ["NvimTreeFolderArrowClosed"] = { fg = "#325d68" },
  ["NvimTreeFolderArrowOpen"] = { fg = "#268bd2" },
  ["NvimTreeFolderIcon"] = { fg = "#268bd2" },
  ["NvimTreeFolderName"] = { fg = "#268bd2" },
  ["NvimTreeGitDeleted"] = { fg = "#dc322f" },
  ["NvimTreeGitDirty"] = { fg = "#dc322f" },
  ["NvimTreeGitIgnored"] = { fg = "#446f7a" },
  ["NvimTreeGitNew"] = { fg = "#b58900" },
  ["NvimTreeIndentMarker"] = { fg = "#0d323c" },
  ["NvimTreeNormal"] = { bg = "#002530" },
  ["NvimTreeNormalNC"] = { bg = "#002530" },
  ["NvimTreeOpenedFolderName"] = { fg = "#268bd2" },
  ["NvimTreeRootFolder"] = { fg = "#dc322f", bold = true },
  ["NvimTreeSpecialFile"] = { fg = "#b58900", bold = true },
  ["NvimTreeWinSeparator"] = { fg = "#002530", bg = "#002530" },
  ["NvimTreeWindowPicker"] = { fg = "#dc322f", bg = "#06313c" },
  ["Operator"] = { fg = "#93a1a1", sp = "none" },
  ["PreProc"] = { fg = "#b58900" },
  ["Repeat"] = { fg = "#b58900" },
  ["Special"] = { fg = "#2aa198" },
  ["SpecialChar"] = { fg = "#d33682" },
  ["Statement"] = { fg = "#dc322f" },
  ["StorageClass"] = { fg = "#b58900" },
  ["String"] = { fg = "#859900" },
  ["Structure"] = { fg = "#6c71c4" },
  ["TBTabTitle"] = { fg = "#002b36", bg = "#268bd2" },
  ["Tabline"] = { bg = "#06313c" },
  ["Tag"] = { fg = "#b58900" },
  ["TbBufOff"] = { fg = "#446f7a", bg = "#06313c" },
  ["TbBufOffClose"] = { fg = "#446f7a", bg = "#06313c" },
  ["TbBufOffModified"] = { fg = "#dc322f", bg = "#06313c" },
  ["TbBufOn"] = { fg = "#abb2bf", bg = "#002b36" },
  ["TbBufOnClose"] = { fg = "#dc322f", bg = "#002b36" },
  ["TbBufOnModified"] = { fg = "#859900", bg = "#002b36" },
  ["TbCloseAllBufsBtn"] = { fg = "#002b36", bg = "#dc322f", bold = true },
  ["TbFill"] = { bg = "#06313c" },
  ["TbTabCloseBtn"] = { fg = "#002b36", bg = "#197ec5" },
  ["TbTabNewBtn"] = { fg = "#abb2bf", bg = "#133e49" },
  ["TbTabOff"] = { fg = "#abb2bf", bg = "#06313c" },
  ["TbTabOn"] = { fg = "#dc322f", bg = "#002b36" },
  ["TbThemeToggleBtn"] = { fg = "#abb2bf", bg = "#1b4651", bold = true },
  ["TelescopeBorder"] = { fg = "#1b4651" },
  ["TelescopeMatching"] = { fg = "#268bd2", bg = "#0a3540" },
  ["TelescopeNormal"] = { bg = "none" },
  ["TelescopePreviewTitle"] = { fg = "#002b36", bg = "#268bd2" },
  ["TelescopePromptBorder"] = { fg = "#1b4651" },
  ["TelescopePromptNormal"] = { bg = "none" },
  ["TelescopePromptPrefix"] = { fg = "#dc322f", bg = "none" },
  ["TelescopePromptTitle"] = { fg = "#002b36", bg = "#dc322f" },
  ["TelescopeResultsDiffAdd"] = { fg = "#859900" },
  ["TelescopeResultsDiffChange"] = { fg = "#b58900" },
  ["TelescopeResultsDiffDelete"] = { fg = "#dc322f" },
  ["TelescopeResultsTitle"] = { fg = "#002b36", bg = "#859900" },
  ["TelescopeSelection"] = { fg = "#abb2bf", bg = "#06313c" },
  ["Todo"] = { fg = "#b58900", bg = "#06313c" },
  ["Type"] = { fg = "#b58900", sp = "none" },
  ["Typedef"] = { fg = "#b58900" },
  ["Variable"] = { fg = "#93a1a1" },
  ["WhichKey"] = { fg = "#268bd2" },
  ["WhichKeyDesc"] = { fg = "#dc322f" },
  ["WhichKeyGroup"] = { fg = "#859900" },
  ["WhichKeySeparator"] = { fg = "#446f7a" },
  ["WhichKeyValue"] = { fg = "#859900" },
  ["diffNewFile"] = { fg = "#268bd2" },
  ["diffOldFile"] = { fg = "#eb413e" },
  ["gitcommitBranch"] = { fg = "#cb4b16", bold = true },
  ["gitcommitComment"] = { fg = "#133e49" },
  ["gitcommitDiscarded"] = { fg = "#133e49" },
  ["gitcommitDiscardedFile"] = { fg = "#dc322f", bold = true },
  ["gitcommitDiscardedType"] = { fg = "#268bd2" },
  ["gitcommitHeader"] = { fg = "#6c71c4" },
  ["gitcommitOverflow"] = { fg = "#dc322f" },
  ["gitcommitSelected"] = { fg = "#133e49" },
  ["gitcommitSelectedFile"] = { fg = "#859900", bold = true },
  ["gitcommitSelectedType"] = { fg = "#268bd2" },
  ["gitcommitSummary"] = { fg = "#859900" },
  ["gitcommitUnmergedFile"] = { fg = "#dc322f", bold = true },
  ["gitcommitUnmergedType"] = { fg = "#268bd2" },
  ["gitcommitUntracked"] = { fg = "#133e49" },
  ["gitcommitUntrackedFile"] = { fg = "#b58900" },
}

function M.apply()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.background = M.background
  vim.g.colors_name = M.name
  for group, hl in pairs(M.highlights) do
    vim.api.nvim_set_hl(0, group, hl)
  end
  vim.api.nvim_exec_autocmds("ColorScheme", { pattern = M.name })
end

return M
