return {
  defaults = { lazy = true },
  install = { colorscheme = { "nvchad" } },

  ui = {
    icons = {
      ft = "",
      lazy = "󰂠 ",
      loaded = "",
      not_loaded = "",
    },
  },

  performance = {
    rtp = {
      disabled_plugins = {
        "2html_plugin",
        "tohtml",
        "getscript",
        "getscriptPlugin",
        "gzip",
        "logipat",
        "netrw",
        "netrwPlugin",
        "netrwSettings",
        "netrwFileHandlers",
        "matchit",
        "tar",
        "tarPlugin",
        "rrhelper",
        "spellfile_plugin",
        "vimball",
        "vimballPlugin",
        "zip",
        "zipPlugin",
        "tutor",
        "rplugin",
        "syntax",
        "synmenu",
        "optwin",
        "compiler",
        "bugreport",
        "ftplugin",
        -- 添加更多不必要的插件
        "man",
        "plugin",
        "spellfile",
        "syntax",
        "syntaxcomplete",
        "vimball",
        "vimballPlugin",
        "zip",
        "zipPlugin",
        "tar",
        "tarPlugin",
        "rrhelper",
        "getscript",
        "getscriptPlugin",
        "logipat",
        "netrw",
        "netrwPlugin",
        "netrwSettings",
        "netrwFileHandlers",
        "matchit",
        "2html_plugin",
        "tohtml",
        "gzip",
      },
    },
    -- 添加缓存配置
    cache = {
      enabled = true,
      path = vim.fn.stdpath("cache") .. "/lazy",
    },
    -- 添加检查配置
    check = {
      enabled = false, -- 禁用启动时检查更新
    },
  },
}
